<?php  namespace app\index\controller;
use think\Controller;
use think\Db;
use think\Request;
use think\Session;
use think\View;
class Adv extends Base
{
	public function adv()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5375=input('appletid');
				$var_166=Db::table('applet')->where('id',$var_5375)->find();
				if(!$var_166)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_166);
				$var_113=Db::table('ims_sudu8_page_nav')->where('uniacid',$var_5375)->find();
				$this->assign('bases',$var_113);
				$var_5376=array();
				$var_5376=Db::table('ims_sudu8_page_banner')->where('uniacid',$var_5375)->where('type','banner')->paginate(10,false,['query' =>array('appletid'=>input('appletid'))]);
				if($var_5376->toArray())
				{
					$var_5377=$var_5376->toArray()['data'];
					foreach($var_5377 as $var_5378=>&$var_5379)
					{
						if($var_5379['pic'])
						{
							$var_5379['pic']=remote($var_5375,$var_5379['pic'],1);
						}
						else
						{
							$var_5379['pic']=remote($var_5375,'/image/noimage.jpg',1);
						}
					}
				}
				$var_5380=Db::table('ims_sudu8_page_banner')->where('uniacid',$var_5375)->where('type','banner')->count();
				$this->assign('counts',$var_5380);
				$this->assign('list',$var_5377);
				$this->assign(adv,$var_5376);
			}
			else
			{
				$var_5381=Session::get('usergroup');
				if($var_5381==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5381==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5381==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(adv);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function kadv()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5383=input('appletid');
				$var_760=Db::table('applet')->where('id',$var_5383)->find();
				if(!$var_760)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_760);
				$var_5384=Db::table('ims_sudu8_page_nav')->where('uniacid',$var_5383)->find();
				$this->assign('bases',$var_5384);
				$var_5385=array();
				$var_5385=Db::table('ims_sudu8_page_banner')->where('uniacid',$var_5383)->where('type','bigad')->paginate(10,false,['query' =>array('appletid'=>input('appletid'))]);
				if($var_5385->toArray())
				{
					$var_5386=$var_5385->toArray()['data'];
					foreach($var_5386 as $var_130=>&$var_5387)
					{
						if($var_5387['pic'])
						{
							$var_5387['pic']=remote($var_5383,$var_5387['pic'],1);
						}
						else
						{
							$var_5387['pic']=remote($var_5383,'/image/noimage.jpg',1);
						}
					}
				}
				$var_240=Db::table('ims_sudu8_page_banner')->where('uniacid',$var_5383)->where('type','bigad')->count();
				$this->assign('list',$var_5386);
				$this->assign('counts',$var_240);
				$this->assign(adv,$var_5385);
			}
			else
			{
				$var_5388=Session::get('usergroup');
				if($var_5388==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5388==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5388==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(kadv);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function sadv()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5390=input('appletid');
				$var_5391=Db::table('applet')->where('id',$var_5390)->find();
				if(!$var_5391)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_5391);
				$var_5392=Db::table('ims_sudu8_page_nav')->where('uniacid',$var_5390)->find();
				$this->assign('bases',$var_5392);
				$var_5393=array();
				$var_5393=Db::table('ims_sudu8_page_banner')->where('uniacid',$var_5390)->where('type','miniad')->paginate(10,false,['query' =>array('appletid'=>input('appletid'))]);
				if($var_5393->toArray())
				{
					$var_5394=$var_5393->toArray()['data'];
					foreach($var_5394 as $v_1=>&$var_255)
					{
						if($var_255['pic'])
						{
							$var_255['pic']=remote($var_5390,$var_255['pic'],1);
						}
						else
						{
							$var_255['pic']=remote($var_5390,'/image/noimage.jpg',1);
						}
					}
				}
				$var_5395=Db::table('ims_sudu8_page_banner')->where('uniacid',$var_5390)->where('type','miniad')->count();
				$this->assign('list',$var_5394);
				$this->assign('counts',$var_5395);
				$this->assign(adv,$var_5393);
			}
			else
			{
				$var_5396=Session::get('usergroup');
				if($var_5396==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5396==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5396==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(sadv);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function tadv()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5398=input('appletid');
				$var_2267=Db::table('applet')->where('id',$var_5398)->find();
				if(!$var_2267)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_2267);
				$var_5399=Db::table('ims_sudu8_page_nav')->where('uniacid',$var_5398)->find();
				$this->assign('bases',$var_5399);
				$var_286=array();
				$var_286=Db::table('ims_sudu8_page_banner')->where('uniacid',$var_5398)->where('type','indexad')->paginate(10,false,['query' =>array('appletid'=>input('appletid'))]);
				if($var_286->toArray())
				{
					$var_68=$var_286->toArray()['data'];
					foreach($var_68 as $var_729=>&$var_5400)
					{
						if($var_5400['pic'])
						{
							$var_5400['pic']=remote($var_5398,$var_5400['pic'],1);
						}
						else
						{
							$var_5400['pic']=remote($var_5398,'/image/noimage.jpg',1);
						}
					}
				}
				$var_5401=Db::table('ims_sudu8_page_banner')->where('uniacid',$var_5398)->where('type','indexad')->count();
				$this->assign('list',$var_68);
				$this->assign('counts',$var_5401);
				$this->assign(adv,$var_286);
			}
			else
			{
				$var_5402=Session::get('usergroup');
				if($var_5402==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5402==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5402==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(tadv);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function add()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5403=input('appletid');
				$var_5404=Db::table('applet')->where('id',$var_5403)->find();
				if(!$var_5404)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_5404);
				$var_5405=Db::table('ims_sudu8_page_nav')->where('uniacid',$var_5403)->find();
				$this->assign('bases',$var_5405);
				$var_5406=input('picid');
				$var_1144=array();
				if($var_5406)
				{
					$var_1144=Db::table('ims_sudu8_page_banner')->where('id',$var_5406)->find();
					if($var_1144['pic'])
					{
						$var_1144['pic']=remote($var_5403,$var_1144['pic'],1);
					}
				}
				else
				{
					$var_5406=0;
				}
				$this->assign('idval',$var_5406);
				$this->assign('pics',$var_1144);
			}
			else
			{
				$var_5407=Session::get('usergroup');
				if($var_5407==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5407==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5407==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(add);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function save()
	{
		$var_5409=array();
		$var_5410=input('picid');
		$var_5409['uniacid']=input('appletid');
		$var_5411=$_POST['num'];
		if($var_5411)
		{
			$var_5409['num']=$var_5411;
		}
		$var_5412=input('type');
		if($var_5412)
		{
			$var_5409['type']=$var_5412;
		}
		$var_5413=input('flag');
		if($var_5413!==false)
		{
			$var_5409['flag']=$var_5413;
		}
		else
		{
			$var_5409['flag']=1;
		}
		$var_45=input('commonuploadpic');
		if($var_45)
		{
			$var_5409['pic']=remote($var_5409['uniacid'],$var_45,2);
		}
		$var_5414=input('url');
		if($var_5414)
		{
			$var_5409['url']=$var_5414;
		}
		$var_5415=input('descp');
		if($var_5415)
		{
			$var_5409['descp']=$var_5415;
		}
		if($var_5410)
		{
			$var_5416=Db::table('ims_sudu8_page_banner')->where('id',$var_5410)->update($var_5409);
		}
		else
		{
			$var_5416=Db::table('ims_sudu8_page_banner')->insert($var_5409);
		}
		if($var_5416)
		{
			$this->success('基础信息更新成功！');
		}
		else
		{
			$this->error('基础信息更新失败，没有修改项！');
			exit;
		}
	}
	function onepic_uploade($v_1)
	{
		$var_14=request()->file($v_1);
		if(isset($var_14))
		{
			$var_5418=upload_img();
			$var_5419=$var_14->move($var_5418);
			if($var_5419)
			{
				$var_5420=ROOT_HOST.'/upimages/'.date('Ymd',time()).'/'.$var_5419->getFilename();
				return $var_5420;
			}
		}
	}
	public function del()
	{
		$var_5422['id']=input('picid');
		$var_5423=Db::table('ims_sudu8_page_banner')->where($var_5422)->delete();
		if($var_5423)
		{
			$this->success('删除成功');
		}
		else
		{
			$this->success('删除失败');
		}
	}
}
?>