<?php  namespace app\index\controller;
use think\Controller;
use think\Db;
use think\Request;
use think\Session;
use think\View;
class Coupon extends Base
{
	public function index()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5538=input('appletid');
				$var_5539=Db::table('applet')->where('id',$var_5538)->find();
				if(!$var_5539)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_5539);
				$var_5540=Db::table('ims_sudu8_page_coupon')->where('uniacid',$var_5538)->order('num desc')->paginate(10,false,['query' =>array('appletid'=>$var_5538)]);
				$var_613=Db::table('ims_sudu8_page_coupon')->where('uniacid',$var_5538)->order('num desc')->count();
				$var_201=$var_5540->toArray();
				$var_5541=time();
				foreach($var_201['data'] as $var_5542=>&$var_5543)
				{
					if($var_5543['etime']==0)
					{
						$var_5543['status']=1;
					}
					else
					{
						if($var_5543['etime']>$var_5541)
						{
							$var_5543['status']=1;
						}
						else
						{
							$var_5543['status']=2;
						}
					}
				}
				$this->assign('coupon',$var_201);
				$this->assign('counts',$var_613);
			}
			else
			{
				$var_5544=Session::get('usergroup');
				if($var_5544==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5544==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5544==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(index);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function userrecord()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5546=input('appletid');
				$var_5547=input('openid');
				if($var_5547)
				{
					$var_5548=Db::table('applet')->where('id',$var_5546)->find();
					if(!$var_5548)
					{
						$this->error('找不到对应的小程序！');
					}
					$this->assign('applet',$var_5548);
					$var_425=Db::table('ims_sudu8_page_coupon_user')->alias('a')->join('ims_sudu8_page_coupon b','a.cid = b.id','left')->join('ims_sudu8_page_user c','a.uid = c.id','left')->where('a.uniacid',$var_5546)->where('c.openid',$var_5547)->order('a.cid desc,a.ltime desc,b.num desc')->field('a.*,b.title,c.nickname')->paginate(10,false,['query' =>array('appletid' =>input('appletid'),'openid'=>input('openid'))]);
					$var_5549=Db::table('ims_sudu8_page_coupon_user')->alias('a')->join('ims_sudu8_page_coupon b','a.cid = b.id','left')->join('ims_sudu8_page_user c','a.uid = c.id','left')->where('a.uniacid',$var_5546)->where('c.openid',$var_5547)->order('a.cid desc,a.ltime desc,b.num desc')->field('a.*,b.title,c.nickname')->count();
					$var_5550=$var_425->toArray();
					$var_363=$var_5550['data'];
					if($var_363)
					{
						foreach($var_363 as $var_5551=>$var_5548)
						{
							if($var_5548['utime']!=0)
							{
								$var_363[$var_5551]['utimetwo']=date('Y-m-d H:i:s',$var_5548['utime']);
							}
							else
							{
								$var_363[$var_5551]['utimetwo']=0;
							}
						}
					}
					$this->assign('coupon',$var_425);
					$this->assign('coupontwo',$var_363);
					$this->assign('counts',$var_5549);
				}
				else
				{
					$var_5548=Db::table('applet')->where('id',$var_5546)->find();
					if(!$var_5548)
					{
						$this->error('找不到对应的小程序！');
					}
					$this->assign('applet',$var_5548);
					$var_425=Db::table('ims_sudu8_page_coupon_user')->alias('a')->join('ims_sudu8_page_coupon b','a.cid = b.id','left')->join('ims_sudu8_page_user c','a.uid = c.id','left')->where('a.uniacid',$var_5546)->order('a.cid desc,a.ltime desc,b.num desc')->field('a.*,b.title,c.nickname')->paginate(10,false,['query' =>array('appletid' =>input('appletid'))]);
					$var_5549=Db::table('ims_sudu8_page_coupon_user')->alias('a')->join('ims_sudu8_page_coupon b','a.cid = b.id','left')->join('ims_sudu8_page_user c','a.uid = c.id','left')->where('a.uniacid',$var_5546)->order('a.cid desc,a.ltime desc,b.num desc')->field('a.*,b.title,c.nickname')->count();
					$var_5550=$var_425->toArray();
					$var_363=$var_5550['data'];
					if($var_363)
					{
						foreach($var_363 as $var_5551=>$var_5548)
						{
							if($var_5548['utime']!=0)
							{
								$var_363[$var_5551]['utimetwo']=date('Y-m-d H:i:s',$var_5548['utime']);
							}
							else
							{
								$var_363[$var_5551]['utimetwo']=0;
							}
						}
					}
					$this->assign('coupon',$var_425);
					$this->assign('coupontwo',$var_363);
					$this->assign('counts',$var_5549);
				}
			}
			else
			{
				$var_5552=Session::get('usergroup');
				if($var_5552==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5552==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5552==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(userrecord);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function userrecorddel()
	{
		$var_240=input('id');
		$var_5553=Db::table('ims_sudu8_page_coupon_user')->where('id',$var_240)->delete();
		if($var_5553)
		{
			$this->success('优惠券领取记录删除成功');
		}
		else
		{
			$this->error('优惠券领取记录删除失败');
		}
	}
	public function userrecordhx()
	{
		$var_1401=input('id');
		$var_5554['utime']=time();
		$var_5554['flag']=1;
		$var_5554['utime']=time();
		$var_5555=Db::table('ims_sudu8_page_coupon_user')->where('id',$var_1401)->update($var_5554);
		if($var_5555)
		{
			$this->success('核销成功');
		}
		else
		{
			$this->error('核销失败');
		}
	}
	public function set()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5557=input('appletid');
				$var_5558=Db::table('applet')->where('id',$var_5557)->find();
				if(!$var_5558)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_5558);
				$var_5559=Db::table('ims_sudu8_page_coupon_set')->where('uniacid',$var_5557)->find();
				$this->assign(set,$var_5559);
			}
			else
			{
				$var_5560=Session::get('usergroup');
				if($var_5560==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5560==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5560==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(set);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function setsave()
	{
		$var_5562=array();
		$var_5563=input('appletid');
		$var_5564=input('flag');
		if(!$var_5564)
		{
			$var_5564=0;
		}
		$var_5562=array('flag' =>$var_5564,'uniacid' =>$var_5563);
		$var_1134=Db::table('ims_sudu8_page_coupon_set')->where('uniacid',$var_5563)->find();
		if($var_1134)
		{
			$var_5565=Db::table('ims_sudu8_page_coupon_set')->where('uniacid',$var_5563)->update($var_5562);
		}
		else
		{
			$var_5565=Db::table('ims_sudu8_page_coupon_set')->insert($var_5562);
		}
		if($var_5565)
		{
			$this->success('设置修改成功');
		}
		else
		{
			$this->error('设置修改失败，没有修改项');
		}
	}
	public function hxmm()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5567=input('appletid');
				$var_5568=Db::table('applet')->where('id',$var_5567)->find();
				if(!$var_5568)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_5568);
				$var_5569=Db::table('ims_sudu8_page_base')->where('uniacid',$var_5567)->find();
				$this->assign(hxmm,$var_5569);
			}
			else
			{
				$var_5570=Session::get('usergroup');
				if($var_5570==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5570==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5570==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(hxmm);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function hxsave()
	{
		$var_5572=array();
		$var_5573=input('appletid');
		if(!input(hxmm))
		{
			$this->error('标题不能为空！');
		}
		$var_5572[hxmm]=input(hxmm);
		$var_5574=Db::table('ims_sudu8_page_base')->where('uniacid',$var_5573)->update($var_5572);
		if($var_5574)
		{
			$this->success('核销密码更新成功！');
		}
		else
		{
			$this->error('核销密码更新失败，没有修改项！');
			exit;
		}
	}
	public function add()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5576=input('appletid');
				$var_5577=Db::table('applet')->where('id',$var_5576)->find();
				if(!$var_5577)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_5577);
				$var_5578=input('couponid');
				$var_5579='';
				if($var_5578)
				{
					$var_5579=Db::table('ims_sudu8_page_coupon')->where('uniacid',$var_5576)->where('id',$var_5578)->find();
				}
				else
				{
					$var_5578=0;
				}
				$this->assign('couponid',$var_5578);
				$this->assign('couponinfo',$var_5579);
			}
			else
			{
				$var_331=Session::get('usergroup');
				if($var_331==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_331==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_331==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(add);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function save()
	{
		$var_5581=array();
		$var_5581['uniacid']=input('appletid');
		$var_5581['num']=input('num');
		if(!input('title'))
		{
			$this->error('标题不能为空！');
		}
		$var_5581['title']=input('title');
		$var_5581['color']='#'.input('color');
		if(!input('price'))
		{
			$this->error('优惠价不能为空！');
		}
		$var_5581['price']=input('price');
		$var_5581['pay_money']=input('pay_money');
		if(!input('counts'))
		{
			$var_5581['counts']=-1;
		}
		else
		{
			$var_5581['counts']=input('counts');
		}
		$var_5581['xz_count']=input('xz_count');
		if(input('btime'))
		{
			$var_5581['btime']=strtotime(input('btime'));
		}
		else
		{
			$var_5581['btime']=0;
		}
		if(input('etime'))
		{
			$var_5581['etime']=strtotime(input('etime'));
		}
		else
		{
			$var_5581['etime']=0;
		}
		$var_5582=input('flag');
		if(!$var_5582)
		{
			$var_5582=0;
		}
		$var_5581['flag']=$var_5582;
		$var_5583=input('couponid');
		if($var_5583)
		{
			$var_1162=Db::table('ims_sudu8_page_coupon')->where('id',$var_5583)->update($var_5581);
		}
		else
		{
			$var_1162=Db::table('ims_sudu8_page_coupon')->insert($var_5581);
		}
		if($var_1162)
		{
			$this->success('优惠券更新成功！',Url('Coupon/index').'?appletid='.$var_5581['uniacid']);
		}
		else
		{
			$this->error('优惠券更新失败，没有修改项！');
			exit;
		}
	}
	public function del()
	{
		$var_5585=input('couponid');
		$var_5586=Db::table('ims_sudu8_page_coupon')->where('id',$var_5585)->delete();
		Db::table('ims_sudu8_page_coupon_user')->where('cid',$var_5585)->delete();
		if($var_5586)
		{
			$this->success('删除成功');
		}
		else
		{
			$this->success('删除失败');
		}
	}
}
?>