<?php  namespace app\index\controller;
use think\Controller;
use think\Db;
use think\Request;
use think\Session;
use think\View;
class Cprinter extends Base
{
	public function index()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5588=input('appletid');
				$var_5589=Db::table('applet')->where('id',$var_5588)->find();
				if(!$var_5589)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_5589);
				$var_5590=Db::table('ims_sudu8_page_food_printer')->where('uniacid',$var_5588)->find();
				$this->assign('bases',$var_5590);
			}
			else
			{
				$var_5591=Session::get('usergroup');
				if($var_5591==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5591==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5591==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(index);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function save()
	{
		$var_1593=input('appletid');
		$var_5593=array();
		$var_5593['status']=$_POST['status'];
		$var_5594=$_POST['pname'];
		if($var_5594)
		{
			$var_5593['pname']=$var_5594;
		}
		else
		{
			$this->error('打印机名称不能为空！');
			exit;
		}
		$var_5595=$_POST['title'];
		if($var_5595)
		{
			$var_5593['title']=$var_5595;
		}
		else
		{
			$this->error('头部标题不能为空！');
			exit;
		}
		$var_5596=$_POST['models'];
		if($var_5596)
		{
			$var_5593['models']=$var_5596;
		}
		else
		{
			$this->error('请选择打印机型号！');
			exit;
		}
		$var_779=$_POST['nid'];
		if($var_779)
		{
			$var_5593['nid']=trim($var_779);
		}
		else
		{
			$this->error('打印机终端号不能为空！');
			exit;
		}
		$var_5597=$_POST['nkey'];
		if($var_5597)
		{
			$var_5593['nkey']=trim($var_5597);
		}
		else
		{
			$this->error('终端号秘钥不能为空！');
			exit;
		}
		$var_5598=$_POST['uid'];
		if($var_5598)
		{
			$var_5593['uid']=trim($var_5598);
		}
		else
		{
			$this->error('用户id不能为空！');
			exit;
		}
		$var_5599=$_POST['apikey'];
		if($var_5599)
		{
			$var_5593['apikey']=trim($var_5599);
		}
		else
		{
			$this->error('秘钥不能为空！');
			exit;
		}
		$var_5593['createtime']=time();
		$var_5600=Db::table('ims_sudu8_page_food_printer')->where('uniacid',$var_1593)->count();
		if($var_5600>0)
		{
			$var_5601=Db::table('ims_sudu8_page_food_printer')->where('uniacid',$var_1593)->update($var_5593);
		}
		else
		{
			$var_5593['uniacid']=$var_1593;
			$var_5601=Db::table('ims_sudu8_page_food_printer')->insert($var_5593);
		}
		if($var_5601)
		{
			$this->success('打印机基本配置更新成功！');
		}
		else
		{
			$this->error('打印机基本配置更新失败，没有修改项！');
			exit;
		}
	}
	function onepic_uploade($v_1)
	{
		$var_5603=request()->file($v_1);
		if(isset($var_5603))
		{
			$var_5604=upload_img();
			$var_5605=$var_5603->validate(['ext'=>'jpg,png,gif,jpeg'])->move($var_5604);
			if($var_5605)
			{
				$var_5606=ROOT_HOST.'/upimages/'.date('Ymd',time()).'/'.$var_5605->getFilename();
				return $var_5606;
			}
		}
	}
	public function getimg()
	{
		$var_5608=$_POST['id'];
		$var_486=Db::table('image_url')->where('appletid',$var_5608)->select();
		if($var_486)
		{
			return $var_486;
		}
	}
	public function del()
	{
		$var_5610=input('id');
		$var_5611=Db::table('image_url')->where('id',$var_5610)->delete();
		if($var_5611)
		{
			return 1;
		}
		else
		{
			$this->error('删除失败！');
		}
	}
}
?>