<?php  namespace app\index\controller;
use think\Controller;
use think\Db;
use think\Request;
use think\Session;
use think\View;
class Customers extends Base
{
	public function index()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5653=input('appletid');
				$var_5654=Db::table('applet')->where('id',$var_5653)->find();
				if(!$var_5654)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_5654);
				$var_5655=Db::table('ims_sudu8_page_customer_base')->where('uniacid',$var_5653)->find();
				$this->assign('base',$var_5655);
			}
			else
			{
				$var_5656=Session::get('usergroup');
				if($var_5656==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5656==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5656==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(index);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function reply()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5495=input('appletid');
				$var_5657=Db::table('applet')->where('id',$var_5495)->find();
				if(!$var_5657)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_5657);
				$var_5658=Db::table('ims_sudu8_page_customer_reply')->where('uniacid',$var_5495)->order('id desc')->select();
				foreach($var_5658 as $var_5659=>$var_5660)
				{
					if($var_5660['type']==3)
					{
						$var_5661=unserialize($var_5660['content']);
						$var_5658[$var_5659]['content']='消息标题：'.$var_5661['title'].'<br>小程序页面路径：'.$var_5661['pagepath'].'<br>小程序卡片的封面图片media_id：'.$var_5661['picurl'];
					}
					if($var_5660['type']==4)
					{
						$var_5661=unserialize($var_5660['content']);
						$var_5658[$var_5659]['content']='消息标题：'.$var_5661['title'].'<br>描述：'.$var_5661['desc'].'<br>图文消息链接：'.$var_5661['url'].'<br>图文消息的图片地址：'.$var_5661['thumb_url'];
					}
					if($var_5660['type']==2)
					{
						$var_5658[$var_5659]['content']='图片media_id：'.$var_5660['content'];
					}
				}
				$this->assign('nav',$var_5658);
			}
			else
			{
				$var_5662=Session::get('usergroup');
				if($var_5662==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5662==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5662==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(reply);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function add()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5664=input('appletid');
				$var_5665=Db::table('applet')->where('id',$var_5664)->find();
				if(!$var_5665)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_5665);
				$var_5666=input('id');
				$var_187=array();
				if($var_5666)
				{
					$var_187=Db::table('ims_sudu8_page_customer_reply')->where('uniacid',$var_5664)->where('id',$var_5666)->find();
					if($var_187['type']==1|| $var_187['type']==2)
					{
						$var_187['title']='';
						$var_187['pagepath']='';
						$var_187['picurl']='';
						$var_187['desc']='';
						$var_187['url']='';
						$var_187['thumb_url']='';
					}
					if($var_187['type']==4)
					{
						$var_5667=unserialize($var_187['content']);
						$var_187['title']=$var_5667['title'];
						$var_187['desc']=$var_5667['desc'];
						$var_187['url']=$var_5667['url'];
						$var_187['thumb_url']=$var_5667['thumb_url'];
						$var_187['content']='';
						$var_187['pagepath']='';
						$var_187['picurl']='';
					}
					if($var_187['type']==3)
					{
						$var_5667=unserialize($var_187['content']);
						$var_187['title']=$var_5667['title'];
						$var_187['picurl']=$var_5667['picurl'];
						$var_187['pagepath']=$var_5667['pagepath'];
						$var_187['content']='';
						$var_187['desc']='';
						$var_187['url']='';
						$var_187['thumb_url']='';
					}
				}
				$this->assign('nav',$var_187);
				$this->assign('cid',$var_5666);
			}
			else
			{
				$var_5668=Session::get('usergroup');
				if($var_5668==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5668==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5668==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(add);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function help(){
        if(check_login())
        {
            if(powerget())
            {
                $var_5653=input('appletid');
                $var_5654=Db::table('applet')->where('id',$var_5653)->find();
                if(!$var_5654)
                {
                    $this->error('找不到对应的小程序！');
                }
                $this->assign('applet',$var_5654);
                $var_5655=Db::table('ims_sudu8_page_customer_base')->where('uniacid',$var_5653)->find();
                $this->assign('base',$var_5655);
            }
            else
            {
                $var_5656=Session::get('usergroup');
                if($var_5656==1)
                {
                    $this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
                }
                if($var_5656==2)
                {
                    $this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
                }
                if($var_5656==3)
                {
                    $this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
                }
            }
            return $this->fetch(help);
        }
        else
        {
            $this->redirect('Login/index');
        }
    }

	public function save()
	{
		$var_5670=array();
		$var_5670['uniacid']=input('appletid');
		$var_357=input('id');
		$var_5671=input('openid');
		if($var_5671)
		{
			$var_5670['openid']=$var_5671;
		}
		if($var_357!=0)
		{
			$var_5672=Db::table('ims_sudu8_page_customer_base')->where('uniacid',$var_5670['uniacid'])->update($var_5670);
		}
		else
		{
			$var_5672=Db::table('ims_sudu8_page_customer_base')->insert($var_5670);
		}
		if($var_5672)
		{
			$this->success('客服设置信息更新成功！');
		}
		else
		{
			$this->error('客服设置更新失败，没有修改项！');
			exit;
		}
	}
	public function savereply()
	{
		$var_5674=array();
		$var_5674['uniacid']=input('appletid');
		$var_5675=intval(input('id'));
		$var_5676=input('type');
		if($var_5676)
		{
			$var_5674['type']=$var_5676;
		}
		if($var_5676==1)
		{
			$var_5674['content']=input('content');
		}
		else if($var_5676==2)
		{
			$var_255=input('picurl');
			$var_5674['content']=$var_255;
		}
		else if($var_5676==3)
		{
			$var_5674['content']['title']=input('title');
			$var_5674['content']['picurl']=input('picurl');
			$var_5674['content']['pagepath']=input('pagepath');
			$var_5674['content']=serialize($var_5674['content']);
		}
		else if($var_5676==4)
		{
			$var_5675=input('id');
			$var_5674['content']['title']=input('title');
			$var_5674['content']['desc']=input('desc');
			$var_5674['content']['url']=input('url');
			$var_5674['content']['thumb_url']=input('thumb_url');
			$var_5674['content']=serialize($var_5674['content']);
		}
		$var_5677=input('flag');
		if($var_5677)
		{
			$var_5674['flag']=$var_5677;
		}
		if($var_5675!=0)
		{
			$var_5678=Db::table('ims_sudu8_page_customer_reply')->where('uniacid',$var_5674['uniacid'])->where('id',$var_5675)->update($var_5674);
		}
		else
		{
			$var_5678=Db::table('ims_sudu8_page_customer_reply')->insert($var_5674);
		}
		if($var_5678)
		{
			$this->success('客服自动回复信息更新成功！');
		}
		else
		{
			$this->error('客服自动回复信息更新失败，没有修改项！');
			exit;
		}
	}
	public function http_post_data($v_1,$v_2)
	{
		$var_5680=curl_init();
		curl_setopt($var_5680,CURLOPT_POST,1);
		curl_setopt($var_5680,CURLOPT_URL,$v_1);
		curl_setopt($var_5680,CURLOPT_POSTFIELDS,$v_2);
		curl_setopt($var_5680,CURLOPT_HTTPHEADER,array('Content-Type: application/json; charset=utf-8','Content-Length: ' .strlen($v_2)));
		ob_start();
		curl_exec($var_5680);
		$var_5681=ob_get_contents();
		ob_end_clean();
		$var_5682=curl_getinfo($var_5680,CURLINFO_HTTP_CODE);
		return $var_5681;
	}
	function onepic_uploade($v_3)
	{
		$var_5683=request()->file($v_3);
		if(isset($var_5683))
		{
			$var_3376=upload_img();
			$var_1177=$var_5683->move($var_3376);
			if($var_1177)
			{
				$var_327=ROOT_HOST.'/upimages/'.date('Ymd',time()).'/'.$var_1177->getFilename();
				return $var_327;
			}
		}
	}
	public function delete()
	{
		$var_5685=input('appletid');
		$var_5686=input('id');
		$var_5687=array('uniacid'=>$var_5685,'id'=>$var_5686);
		$var_5688=Db::table('ims_sudu8_page_customer_reply')->where($var_5687)->delete();
		if($var_5688)
		{
			$this->success('删除成功');
		}
		else
		{
			$this->success('删除失败');
		}
	}
}
?>