<?php  namespace app\index\controller;
use think\Controller;
use think\Db;
use think\Request;
use think\Session;
use think\View;
class Cz extends Base
{
	public function index()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_408=input('appletid');
				$var_5853=Db::table('applet')->where('id',$var_408)->find();
				if(!$var_5853)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_5853);
				$var_5854=Db::table('ims_sudu8_page_rechargeconf')->where('uniacid',$var_408)->find();
				$this->assign('rechargeconf',$var_5854);
			}
			else
			{
				$var_507=Session::get('usergroup');
				if($var_507==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_507==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_507==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(index);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function del()
	{
		$var_113=input('appletid');
		$var_5855=input('cz');
		$var_1203=Db::table('ims_sudu8_page_recharge')->where('id',$var_5855)->where('uniacid',$var_113)->delete();
		if($var_1203)
		{
			$this->success('删除成功！');
		}
		else
		{
			$this->error('删除失败，没有删除项！');
			exit;
		}
	}
	public function save()
	{
		$var_5856=input('appletid');
		$var_486=input('title');
		if($var_486)
		{
			$var_3511['title']=$var_486;
		}
		else
		{
			$var_3511['title']='';
		}
		$var_166=input('score');
		if($var_166)
		{
			if($var_166<0)
			{
				$var_3511['score']=0;
			}
			else
			{
				$var_3511['score']=$var_166;
			}
		}
		else
		{
			$var_3511['score']=0;
		}
		$var_25=input('money');
		if($var_25)
		{
			if($var_25<0)
			{
				$var_3511['money']=0;
			}
			else
			{
				$var_3511['money']=$var_25;
			}
		}
		else
		{
			$var_3511['money']=0;
		}
		$var_161=input('score_shoppay');
		if(!$var_161|| $var_161<0)
		{
			$var_3511['score_shoppay']=0;
		}
		else
		{
			$var_3511['score_shoppay']=$var_161;
		}
		$var_3511['uniacid']=$var_5856;
		$var_5857=Db::table('ims_sudu8_page_rechargeconf')->where('uniacid',$var_5856)->find();
		if($var_5857)
		{
			$var_5858=Db::table('ims_sudu8_page_rechargeconf')->where('uniacid',$var_5856)->update($var_3511);
		}
		else
		{
			$var_5858=Db::table('ims_sudu8_page_rechargeconf')->insert($var_3511);
		}
		if($var_5858)
		{
			$this->success('更新成功！');
		}
		else
		{
			$this->error('更新失败，没有修改项！');
			exit;
		}
	}
	public function guiz()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5860=input('appletid');
				$var_1144=Db::table('applet')->where('id',$var_5860)->find();
				if(!$var_1144)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_1144);
				$var_5861=Db::table('ims_sudu8_page_recharge')->where('uniacid',$var_5860)->order('money asc')->paginate(10,false,['query' =>array('appletid'=>input('appletid'))]);
				$var_5862=Db::table('ims_sudu8_page_recharge')->where('uniacid',$var_5860)->count();
				$this->assign('counts',$var_5862);
				$this->assign(guiz,$var_5861);
			}
			else
			{
				$var_5863=Session::get('usergroup');
				if($var_5863==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5863==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5863==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(guiz);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function add()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_5864=input('appletid');
				$var_5865=Db::table('applet')->where('id',$var_5864)->find();
				if(!$var_5865)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_5865);
				$var_5866=input('cz');
				$var_5867=array();
				if($var_5866)
				{
					$var_5867=Db::table('ims_sudu8_page_recharge')->where('id',$var_5866)->find();
				}
				else
				{
					$var_5866=0;
				}
				$this->assign('recharge',$var_5867);
				$this->assign('cz',$var_5866);
			}
			else
			{
				$var_5868=Session::get('usergroup');
				if($var_5868==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_5868==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_5868==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(add);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function guizsave()
	{
		$var_5870=input('cz');
		$var_5871=input('appletid');
		$var_5872=input('money');
		if($var_5872)
		{
			if($var_5872<0)
			{
				$var_5873['money']=0;
			}
			else
			{
				$var_5873['money']=$var_5872;
			}
		}
		else
		{
			$var_5873['money']=0;
		}
		$var_5874=input('getmoney');
		if($var_5874)
		{
			if($var_5874<0)
			{
				$var_5873['getmoney']=0;
			}
			else
			{
				$var_5873['getmoney']=$var_5874;
			}
		}
		else
		{
			$var_5873['getmoney']=0;
		}
		$var_5875=input('getscore');
		if($var_5875)
		{
			if($var_5875<0)
			{
				$var_5873['getscore']=0;
			}
			else
			{
				$var_5873['getscore']=$var_5875;
			}
		}
		else
		{
			$var_5873['getscore']=0;
		}
		$var_5873['uniacid']=$var_5871;
		if($var_5870)
		{
			$var_5876=Db::table('ims_sudu8_page_recharge')->where('uniacid',$var_5871)->where('id',$var_5870)->update($var_5873);
		}
		else
		{
			$var_5876=Db::table('ims_sudu8_page_recharge')->insert($var_5873);
		}
		if($var_5876)
		{
			$this->success('规则更新成功！',Url('Cz/guiz').'?appletid='.$var_5871);
		}
		else
		{
			$this->error('更新失败，没有修改项！');
			exit;
		}
	}
}
?>