<?php  namespace app\index\controller;
use think\Controller;
use think\Db;
use think\Request;
use think\Session;
use think\View;
class Fx extends Base
{
	public function base()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_6109=input('appletid');
				$var_6110=Db::table('applet')->where('id',$var_6109)->find();
				if(!$var_6110)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_6110);
				$v_3=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6109)->find();
				if($v_3)
				{
					if($v_3['sq_thumb'])
					{
						$v_3['sq_thumb']=remote($var_6109,$v_3['sq_thumb'],1);
					}
				}
				$this->assign('item',$v_3);
			}
			else
			{
				$var_6111=Session::get('usergroup');
				if($var_6111==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_6111==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_6111==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(base);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function extension()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_175=input('appletid');
				$var_6113=Db::table('applet')->where('id',$var_175)->find();
				if(!$var_6113)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_6113);
				$var_1304=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_175)->find();
				$var_1304['thumb']=remote($var_175,$var_1304['thumb'],1);
				$this->assign('item',$var_1304);
			}
			else
			{
				$var_6114=Session::get('usergroup');
				if($var_6114==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_6114==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_6114==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(extension);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function extensionsave()
	{
		$var_6116=input('appletid');
		$var_6117=input('commonuploadpic');
		if($var_6117==null)
		{
			$this->error('分享推广图不能为空');
			exit;
		}
		$var_6118=array('thumb' =>remote($var_6116,$var_6117,2),);
		$var_6119=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6116)->find();
		if($var_6119)
		{
			$var_6120=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6116)->update($var_6118);
		}
		else
		{
			$var_6120=Db::table('ims_sudu8_page_fx_gz')->insert($var_6118);
		}
		if($var_6120)
		{
			$this->success('分享推广图更新成功！');
		}
		else
		{
			$this->error('分享推广图更新失败，没有修改项！');
			exit;
		}
	}
	public function basesave()
	{
		$var_6122=input('appletid');
		$var_6123=input('fxs_name');
		if(!$var_6123)
		{
			$this->error('分销商名称不能为空');
			exit;
		}
		$var_6124=input('sq_thumb2');
		$var_6125=input('commonuploadpic');
		if(!$var_6125)
		{
			if($var_6124)
			{
				$var_6125=$var_6124;
			}
			else
			{
				$this->error('申请图片不能为空');
				exit;
			}
		}
		else
		{
			$var_6125=remote($var_6122,$var_6125,2);
		}
		$var_6126=array('fxs_name' =>input('fxs_name'),'sq_thumb' =>$var_6125,'uniacid' =>input('appletid'),'fx_cj' =>intval(input('fx_cj')),'one_bili' =>intval(input('one_bili')),'two_bili' =>intval(input('two_bili')),'three_bili' =>intval(input('three_bili')));
		$var_6127=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6122)->find();
		if($var_6127)
		{
			$var_6128=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6122)->update($var_6126);
		}
		else
		{
			$var_6128=Db::table('ims_sudu8_page_fx_gz')->insert($var_6126);
		}
		if($var_6128)
		{
			$this->success('分销基本信息更新成功！');
		}
		else
		{
			$this->error('分销基本信息更新失败，没有修改项！');
			exit;
		}
	}
	function onepic_uploade($v_1)
	{
		$var_6130=request()->file($v_1);
		if(isset($var_6130))
		{
			$var_201=upload_img();
			$var_6131=$var_6130->validate(['ext'=>'jpg,png,gif,jpeg'])->move($var_201);
			if($var_6131)
			{
				$var_6132=ROOT_HOST.'/upimages/'.date('Ymd',time()).'/'.$var_6131->getFilename();
				return $var_6132;
			}
		}
	}
	public function relation()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_6134=input('appletid');
				$var_166=Db::table('applet')->where('id',$var_6134)->find();
				if(!$var_166)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_166);
				$var_6135=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6134)->find();
				$this->assign('item',$var_6135);
			}
			else
			{
				$var_6136=Session::get('usergroup');
				if($var_6136==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_6136==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_6136==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(relation);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function relationsave()
	{
		$var_6138=array('uniacid' =>input('appletid'),'sxj_gx' =>intval(input('sxj_gx')),'fxs_sz' =>intval(input('fxs_sz')),'fxs_sz_val' =>intval(input('fxs_sz_val')));
		$var_6139=input('appletid');
		$var_6140=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6139)->find();
		if($var_6140)
		{
			$var_6141=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6139)->update($var_6138);
		}
		else
		{
			$var_6141=Db::table('ims_sudu8_page_fx_gz')->insert($var_6138);
		}
		if($var_6141)
		{
			$this->success('上下级关系及分销资格更新成功！');
		}
		else
		{
			$this->error('上下级关系及分销资格更新失败，没有修改项！');
			exit;
		}
	}
	public function agree()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_6143=input('appletid');
				$var_6144=Db::table('applet')->where('id',$var_6143)->find();
				if(!$var_6144)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_6144);
				$var_6145=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6143)->find();
				$this->assign('item',$var_6145);
			}
			else
			{
				$var_6146=Session::get('usergroup');
				if($var_6146==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_6146==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_6146==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(agree);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function agreesave()
	{
		$var_6147['fxs_xy']=input('content');
		$var_6148=input('appletid');
		$var_6149=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6148)->find();
		if($var_6149)
		{
			$var_6150=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6148)->update($var_6147);
		}
		else
		{
			$var_6150=Db::table('ims_sudu8_page_fx_gz')->insert($var_6147);
		}
		if($var_6150)
		{
			$this->success('分销商申请协议更新成功！');
		}
		else
		{
			$this->error('分销商申请协议更新失败，没有修改项！');
			exit;
		}
	}
	public function dealer()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_6152=input('appletid');
				$var_6153=input('id');
				$var_252=input('val');
				if($var_6153&& $var_252)
				{
					$var_6154=Db::table('ims_sudu8_page_fx_sq')->where('id',$var_6153)->find();
					Db::table('ims_sudu8_page_fx_sq')->where('id',$var_6153)->update(array('flag'=>$var_252));
					if($var_252==2)
					{
						Db::table('ims_sudu8_page_user')->where('openid',$var_6154['openid'])->where('uniacid',$var_6152)->update(array('fxs'=>2));
					}
					$this->success('审核成功');
				}
				else
				{
					$var_6155=Db::table('applet')->where('id',$var_6152)->find();
					if(!$var_6155)
					{
						$this->error('找不到对应的小程序！');
					}
					$this->assign('applet',$var_6155);
					$var_6154=array();
					$var_6154=Db::table('ims_sudu8_page_fx_sq')->where('uniacid',$var_6152)->where('flag',1)->select();
					$var_6156=Db::table('ims_sudu8_page_user')->where('uniacid',$var_6152)->where('fxs',2)->select();
					foreach($var_6156 as $var_6157=>&$var_6155)
					{
						$var_6155['flag']=2;
						array_push($var_6154,$var_6155);
					}
					foreach($var_6154 as $var_6157=>$var_6155)
					{
						$var_967=Db::table('ims_sudu8_page_user')->where('uniacid',$var_6152)->where('openid',$var_6155['openid'])->find();
						$var_6154[$var_6157]['userinfo']=$var_967;
					}
					$this->assign('users',$var_6154);
				}
			}
			else
			{
				$var_554=Session::get('usergroup');
				if($var_554==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_554==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_554==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(dealer);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function txreply()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_6159=input('appletid');
				$var_6160=Db::table('applet')->where('id',$var_6159)->find();
				if(!$var_6160)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_6160);
				$var_6161=input('op');
				if($var_6161)
				{
					if($var_6161=='shenhe')
					{
						$var_6162=input('id');
						$var_6163=input('val');
						if($var_6163==2)
						{
							$var_6164=Db::table('ims_sudu8_page_fx_tx')->where('uniacid',$var_6159)->where('id',$var_6162)->find();
							$var_6165=$var_6164['openid'];
							$var_6166=$var_6164['money'];
							$var_126=Db::table('ims_sudu8_page_user')->where('uniacid',$var_6159)->where('openid',$var_6165)->find();
							$var_6167=$var_126['fx_getmoney'];
							$var_6168=$var_126['fx_money'];
							$var_6169=$var_126['money'];
							if($var_6164['types']==1)
							{
								$var_6169=$var_6169+$var_6166;
								$var_6167=$var_6167+$var_6166;
								$var_6168=$var_6168;
								$var_6170=array('money' =>$var_6169,'fx_getmoney' =>$var_6167,'fx_money' =>$var_6168);
								Db::table('ims_sudu8_page_user')->where('uniacid',$var_6159)->where('openid',$var_6165)->update($var_6170);
								Db::table('ims_sudu8_page_fx_tx')->where('id',$var_6162)->update(array('flag'=>2,'txtime'=>time()));
								$var_1602['uniacid']=$var_6171;
								$var_1602['orderid']='';
								$var_1602['uid']=$var_126['id'];
								$var_1602['type']='add';
								$var_1602['score']=$var_6166;
								$var_1602['message']='分销提现到余额';
								$var_1602['creattime']=time();
								Db::table('ims_sudu8_page_money')->insert($var_1602);
							}
							if($var_6164['types']==2)
							{
								$var_6172=Db::table('applet')->where('id',$var_6159)->find();
								$var_6165=$var_6164['openid'];
								$var_6166=$var_6164['money'];
								$var_6173=Db::table('ims_sudu8_page_user')->where('uniacid',$var_6159)->where('openid',$var_6165)->find();
								$var_6174=$var_6173['nickname'];
								$var_6175=$var_6172['mchid'];
								$var_45=$var_6172['signkey'];
								$v_7=$var_6172['appID'];
								$var_6176=$var_6172['appSecret'];
								include 'weixin_zf.php';
								$var_842=time();
								$var_6177=$var_6178=date('Y',$var_842).date('m',$var_842).date('d',$var_842).date('H',$var_842).date('i',$var_842).date('s',$var_842).rand(1000,9999);
								$var_6179=new WxpayService($var_6175,$v_7,$var_6176,$var_45);
								$var_6180=$var_6179->createJsBizPackage($var_6165,$var_6166,$var_6177,$var_6174,$var_6171);
								if($var_6180)
								{
									$var_6167=$var_6167+$var_6166;
									$var_6168=$var_6168-$var_6166;
									$var_6170=array('fx_getmoney' =>$var_6167,'fx_money' =>$var_6168);
									Db::table('ims_sudu8_page_user')->where('uniacid',$var_6159)->where('openid',$var_6165)->update($var_6170);
									Db::table('ims_sudu8_page_fx_tx')->where('id',$var_6162)->update(array('flag'=>2,'txtime'=>time()));
								}
							}
							if($var_6164['types']==3)
							{
								$var_6169=$var_6169+$var_6166;
								$var_6167=$var_6167+$var_6166;
								$var_6168=$var_6168;
								$var_6170=array('money' =>$var_6169,'fx_getmoney' =>$var_6167,'fx_money' =>$var_6168);
								Db::table('ims_sudu8_page_user')->where('uniacid',$var_6159)->where('openid',$var_6165)->update($var_6170);
								Db::table('ims_sudu8_page_fx_tx')->where('id',$var_6162)->update(array('flag'=>2,'txtime'=>time()));
							}
							$this->success('提现成功 新增/修改成功');
						}
						if($var_6163==3)
						{
							Db::table('ims_sudu8_page_fx_tx')->where('id',$var_6162)->update(array('flag'=>3,'txtime'=>time()));
							$var_6164=Db::table('ims_sudu8_page_fx_tx')->where('id',$var_6162)->where('uniacid',$var_6159)->find();
							$var_6165=$var_6164['openid'];
							$var_6166=$var_6164['money'];
							$var_126=Db::table('ims_sudu8_page_user')->where('openid',$var_6165)->where('uniacid',$var_6159)->find();
							$var_6181=$var_126['fx_money'];
							$var_6182=$var_6181*1+$var_6166*1;
							Db::table('ims_sudu8_page_user')->where('uniacid',$var_6159)->where('openid',$var_6165)->update(array('fx_money'=>$var_6182));
							$this->success('提现 新增/修改成功');
						}
					}
				}
				else
				{
					$var_6164=Db::table('ims_sudu8_page_fx_tx')->where('uniacid',$var_6159)->order('id desc')->select();
					foreach($var_6164 as $var_6183=>&$var_6160)
					{
						$var_126=Db::table('ims_sudu8_page_user')->where('uniacid',$var_6159)->where('openid',$var_6160['openid'])->find();
						$var_6160['userinfo']=$var_126;
						$var_6160['creattime']=date('Y-m-d H:i:s',$var_6160['creattime']);
					}
					$this->assign('sqtx',$var_6164);
				}
			}
			else
			{
				$var_6184=Session::get('usergroup');
				if($var_6184==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_6184==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_6184==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(txreply);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function txset()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_6186=input('appletid');
				$var_1218=Db::table('applet')->where('id',$var_6186)->find();
				if(!$var_1218)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_1218);
				$var_6187=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6186)->find();
				$this->assign('item',$var_6187);
			}
			else
			{
				$var_6188=Session::get('usergroup');
				if($var_6188==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_6188==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_6188==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(txset);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function txsetsave()
	{
		$var_6190=input('appletid');
		$var_6191=input('txmoney');
		$var_6192=input('certtext');
		if(!$var_6192)
		{
			$this->error('apiclient_cert.pem不能为空');
			exit;
		}
		$var_6193=input('keytext');
		if(!$var_6193)
		{
			$this->error('apiclient_key.pem不能为空');
			exit;
		}
		$var_6194=input('catext');
		if(!$var_6194)
		{
			$this->error('rootca.pem不能为空');
			exit;
		}
		$var_100=array('txmoney' =>$var_6191,'uniacid' =>$var_6190,'certtext' =>$var_6192,'keytext' =>$var_6193,'catext' =>$var_6194);
		if($var_6192&& $var_6193&& $var_6194)
		{
			$var_370=ROOT_PATH.'public/Cert/'.$var_6190.'/apiclient_cert.pem';
			$var_6195=ROOT_PATH.'public/Cert/'.$var_6190.'/apiclient_key.pem';
			$var_6196=ROOT_PATH.'public/Cert/'.$var_6190.'/rootca.pem';
			$var_6197=ROOT_PATH.'public/Cert';
			if(!file_exists($var_6197))
			{
				if(mkdir($var_6197))
				{
					$var_30=ROOT_PATH.'public/Cert/'.$var_6190.'/';
					if(!file_exists($var_30))
					{
						mkdir($var_30);
					}
				}
			}
			else
			{
				$var_30=ROOT_PATH.'public/Cert/'.$var_6190.'/';
				if(!file_exists($var_30))
				{
					mkdir($var_30);
				}
			}
			file_put_contents($var_370,$var_6192);
			file_put_contents($var_6195,$var_6193);
			file_put_contents($var_6196,$var_6194);
		}
		$var_6198=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6190)->find();
		if($var_6198)
		{
			$var_23=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6190)->update($var_100);
		}
		else
		{
			$var_23=Db::table('ims_sudu8_page_fx_gz')->insert($var_100);
		}
		if($var_23)
		{
			$this->success('提现设置更新成功！');
		}
		else
		{
			$this->error('提现设置更新失败，没有修改项！');
			exit;
		}
	}
	public function order()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_6199=input('appletid');
				$var_6200=Db::table('applet')->where('id',$var_6199)->find();
				if(!$var_6200)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_6200);
				$var_6201=Db::table('ims_sudu8_page_fx_gz')->where('uniacid',$var_6199)->find();
				$this->assign('item',$var_6201);
				$var_6202=Db::table('ims_sudu8_page_fx_ls')->where('uniacid',$var_6199)->order('id desc')->select();
				foreach($var_6202 as $var_6203=>&$var_6200)
				{
					$var_6204=0;
					$var_6205=0;
					$var_6206=Db::table('ims_sudu8_page_duo_products_order')->where('uniacid',$var_6199)->where('order_id',$var_6200['order_id'])->find();
					$var_6207=unserialize($var_6206['jsondata']);
					$var_6208=$var_6207[0]['one_bili'];
					$var_6209=$var_6207[0]['two_bili'];
					$var_6210=$var_6207[0]['three_bili'];
					$var_6200['gmz']=Db::table('ims_sudu8_page_user')->where('uniacid',$var_6199)->where('openid',$var_6200['openid'])->find();
					if($var_6200['parent_id'])
					{
						$var_6204=1;
						$var_6205=$var_6208;
						$var_6200['v1']=Db::table('ims_sudu8_page_user')->where('uniacid',$var_6199)->where('openid',$var_6200['parent_id'])->find();
						$var_6200['v1']['hmoney']=$var_6200['parent_id_get'];
					}
					else
					{
						$var_6200['v1']='';
					}
					if($var_6200['p_parent_id'])
					{
						$var_6204=2;
						$var_6205=$var_6209;
						$var_6200['v2']=Db::table('ims_sudu8_page_user')->where('uniacid',$var_6199)->where('openid',$var_6200['p_parent_id'])->find();
						$var_6200['v2']['hmoney']=$var_6200['p_parent_id_get'];
					}
					else
					{
						$var_6200['v2']='';
					}
					if($var_6200['p_p_parent_id'])
					{
						$var_6204=3;
						$var_6205=$var_6210;
						$var_6200['v3']=Db::table('ims_sudu8_page_user')->where('uniacid',$var_6199)->where('openid',$var_6200['p_p_parent_id'])->find();
						$var_6200['v3']['hmoney']=$var_6200['p_p_parent_id_get'];
					}
					else
					{
						$var_6200['v3']='';
					}
					$var_6211=Db::table('ims_sudu8_page_duo_products_order')->where('uniacid',$var_6199)->where('order_id',$var_6200['order_id'])->find();
					$var_6200['datas']=unserialize($var_6211['jsondata']);
					$var_6200[order]=$var_6211;
					$var_6200['counts']=count(unserialize($var_6211['jsondata']));
					$var_6200['creattime']=date('Y-m-d H:i',$var_6200['creattime']);
					$var_6200['hxtime']=date('Y-m-d H:i',$var_6211['hxtime']);
					$var_6200['v']=$var_6204;
				}
				$this->assign('orders',$var_6202);
			}
			else
			{
				$var_6212=Session::get('usergroup');
				if($var_6212==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_6212==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_6212==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(order);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
}
?>