<?php  namespace app\index\controller;
use think\Controller;
use think\Db;
use think\Request;
use think\Session;
use think\View;
class Powerfulsh extends Base
{
	public function cate()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_1496=input('appletid');
				$var_45=Db::table('applet')->where('id',$var_1496)->find();
				if(!$var_45)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_45);
				$var_1497=Db::table('ims_sudu8_page_shops_cate')->where('uniacid',$var_1496)->order('num desc')->paginate(10,false,['query' =>array('appletid'=>input('appletid'))]);
				$var_68=Db::table('ims_sudu8_page_shops_cate')->where('uniacid',$var_1496)->order('num desc')->count();
				$this->assign('cates',$var_1497);
				$this->assign('counts',$var_68);
			}
			else
			{
				$var_1498=Session::get('usergroup');
				if($var_1498==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_1498==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_1498==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(cate);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function cateadd()
	{
		$var_1500=input('appletid');
		$var_1501=Db::table('applet')->where('id',$var_1500)->find();
		if(!$var_1501)
		{
			$this->error('找不到对应的小程序！');
		}
		$this->assign('applet',$var_1501);
		$var_1502=intval(input('cateid'));
		$var_1503=Db::table('ims_sudu8_page_shops_cate')->where('uniacid',$var_1500)->where('id',$var_1502)->find();
		if(!$var_1502)
		{
			$var_1502=0;
		}
		$this->assign(cate,$var_1503);
		$this->assign('cateid',$var_1502);
		return $this->fetch(cateadd);
	}
	public function catedel()
	{
		$var_1505=input('appletid');
		$var_1506=input('cateid');
		$var_1507=array('uniacid'=>$var_1505,'id'=>$var_1506);
		$var_1508=Db::table('ims_sudu8_page_shops_cate')->where($var_1507)->delete();
		if($var_1508)
		{
			$this->success('拼团栏目删除成功');
		}
		else
		{
			$this->success('拼团栏目删除失败');
		}
	}
	public function catesave()
	{
		$var_1510=array();
		$var_1511=input('appletid');
		$var_1512=input('num');
		if($var_1512)
		{
			$var_1510['num']=$var_1512;
		}
		else
		{
			$var_1510['num']=1;
		}
		$var_102=input('name');
		if($var_102)
		{
			$var_1510['name']=$var_102;
		}
		else
		{
			$this->error('栏目名称不能为空！');
			exit;
		}
		$var_1510['flag']=input('flag');
		$var_1513=intval(input('cateid'));
		if(!$var_1513)
		{
			$var_1510['uniacid']=$var_1511;
			$var_1514=Db::table('ims_sudu8_page_shops_cate')->insert($var_1510);
		}
		else
		{
			$var_1514=Db::table('ims_sudu8_page_shops_cate')->where('id',$var_1513)->where('uniacid',$var_1511)->update($var_1510);
		}
		if($var_1514)
		{
			$this->success('拼团分类新增/更新成功!',Url('Powerfulsh/cate').'?appletid='.$var_1511);
		}
		else
		{
			$this->error('拼团分类新增/更新更新失败，没有修改项！');
			exit;
		}
	}
	public function tenant()
	{
		if(check_login())
		{
			if(powerget())
			{
				$v_2=input('appletid');
				$var_1516=Db::table('applet')->where('id',$v_2)->find();
				if(!$var_1516)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_1516);
				$var_1517=input('op');
				if($var_1517)
				{
					if($var_1517=='tenantshenhe')
					{
						$var_460=input('shopid');
						$var_1516=Db::table('ims_sudu8_page_shops_shop')->where('uniacid',$v_2)->where('id',$var_460)->update(array('status'=>1));
						if($var_1516)
						{
							if($var_1516)
							{
								$this->success('商家审核通过');
							}
							else
							{
								$this->success('商家审核失败');
							}
						}
					}
					if($var_1517=='tenantcancel')
					{
						$var_460=input('shopid');
						$var_1516=Db::table('ims_sudu8_page_shops_shop')->where('uniacid',$v_2)->where('id',$var_460)->update(array('status'=>2));
						if($var_1516)
						{
							if($var_1516)
							{
								$this->success('商家审核不通过');
							}
							else
							{
								$this->success('商家审核失败');
							}
						}
					}
				}
				else
				{
					$var_1518=Db::table('ims_sudu8_page_shops_shop')->where('uniacid',$v_2)->order('num desc')->paginate(10,false,['query' =>array('appletid'=>input('appletid'))]);
					$var_1519=$var_1518->all();
					if($var_1519)
					{
						foreach($var_1519 as $var_1520=>&$var_1516)
						{
							$var_1521=Db::table('ims_sudu8_page_shops_cate')->where('uniacid',$v_2)->where('id',$var_1516['cid'])->find();
							$var_1516[cate]=$var_1521['name'];
						}
					}
					$var_905=Db::table('ims_sudu8_page_shops_shop')->where('uniacid',$v_2)->order('num desc')->count();
					$this->assign('shoplist',$var_1519);
					$this->assign('shops',$var_1518);
					$this->assign('counts',$var_905);
				}
			}
			else
			{
				$var_1522=Session::get('usergroup');
				if($var_1522==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_1522==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_1522==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(tenant);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function tenantadd()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_1523=input('appletid');
				$var_1524=Db::table('applet')->where('id',$var_1523)->find();
				if(!$var_1524)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_1524);
				$var_1525=input('shopid');
				$var_175=Db::table('ims_sudu8_page_shops_cate')->where('uniacid',$var_1523)->order('num desc')->order('id desc')->select();
				$var_1526='';
				if($var_1525)
				{
					$var_1526=DB::table('ims_sudu8_page_shops_shop')->where('uniacid',$var_1523)->where('id',$var_1525)->find();
					if($var_1526['images'])
					{
						$var_1526['images']=unserialize($var_1526['images']);
						if($var_1526['images'])
						{
							foreach($var_1526['images'] as $var_1527=>&$var_1528)
							{
								$var_1528=remote($var_1523,$var_1528,1);
							}
						}
					}
				}
				else
				{
					$var_1525=0;
				}
				$this->assign('shopid',$var_1525);
				$this->assign('shopinfo',$var_1526);
				$this->assign('listAll',$var_175);
			}
			else
			{
				$var_1529=Session::get('usergroup');
				if($var_1529==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_1529==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_1529==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(tenantadd);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function tenantsave()
	{
		$var_1531=input('appletid');
		$var_426=input('shopid');
		$var_1113=input('cid');
		$var_1532=input('flag');
		if(!$var_1532)
		{
			$var_1532=0;
		}
		$var_1533=input('hot');
		if(!$var_1533)
		{
			$var_1533=0;
		}
		$var_1534=input('username');
		if($var_1534=='')
		{
			$this->error('账号不能为空');
			exit;
		}
		$var_1535=input('password');
		if($var_1535=='')
		{
			$this->error('密码不能为空');
			exit;
		}
		$var_1536=Db::table('ims_sudu8_page_shops_cate')->where('uniacid',$var_1531)->where('id',$var_1113)->find();
		if($var_1536)
		{
			$var_1537=array('uniacid' =>$var_1531,'cid' =>input('cid'),'num' =>input('num'),'flag' =>$var_1532,'hot' =>$var_1533,'username' =>input('username'),'name' =>input('name'),'password' =>input('password'),'intro' =>input('intro'),'worktime' =>input('worktime'),'star' =>input('star'),'tel' =>input('tel'),'address' =>input('address'),'latitude' =>input('latitude'),'longitude' =>input('longitude'),'title' =>input('title'),'descp' =>input('descp'),);
		}
		$var_1212=input('imgsrcs/a');
		if($var_1212)
		{
			foreach($var_1212 as $var_1538=>&$var_1539)
			{
				$var_1539=remote($var_1531,$var_1539,1);
			}
			$var_1537['images']=serialize($var_1212);
		}
		else
		{
			$var_1537['images']=[];
		}
		$var_1540=input('commonuploadpic1');
		if($var_1540)
		{
			$var_1537['logo']=remote($var_1531,$var_1540,2);
		}
		$var_1203=input('commonuploadpic2');
		if($var_1203)
		{
			$var_1537['bg']=remote($var_1531,$var_1203,2);
		}
		if($var_426>0)
		{
			$var_1541=Db::table('ims_sudu8_page_shops_shop')->where('uniacid',$var_1531)->where('id',$var_426)->update($var_1537);
		}
		else
		{
			$var_1542=Db::table('ims_sudu8_page_shops_shop')->where('username',$var_1534)->find();
			if($var_1542)
			{
				$this->error('账号名重复');
				exit;
			}
			$var_1537['uniacid']=$var_1531;
			$var_1541=Db::table('ims_sudu8_page_shops_shop')->insert($var_1537);
		}
		if($var_1541)
		{
			$this->success('店铺信息更新成功！',Url('Powerfulsh/tenant').'?appletid='.$var_1531);
		}
		else
		{
			$this->error('店铺信息更新失败！');
		}
	}
	public function tenantdel()
	{
		$var_1544=input('appletid');
		$var_1545=input('shopid');
		$var_1546=array('uniacid'=>$var_1544,'id'=>$var_1545);
		$var_1547=Db::table('ims_sudu8_page_shops_shop')->where($var_1546)->delete();
		if($var_1547)
		{
			$this->success('商家删除成功');
		}
		else
		{
			$this->success('商家删除失败');
		}
	}
	public function goods()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_187=input('appletid');
				$var_1548=Db::table('applet')->where('id',$var_187)->find();
				if(!$var_1548)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_1548);
				$var_1549=Db::table('ims_sudu8_page_shops_goods')->where('uniacid',$var_187)->paginate(10,false,['query' =>array('appletid'=>input('appletid'))]);
				$var_1550=$var_1549->all();
				if($var_1550)
				{
					foreach($var_1550 as $var_1551=>&$var_1548)
					{
						$var_1548['thumb']=remote($var_187,$var_1548['thumb'],1);
						$var_1552=Db::table('ims_sudu8_page_shops_shop')->where('uniacid',$var_187)->where('id',$var_1548['sid'])->field('name')->find();
						$var_1548['shopname']=$var_1552['name'];
					}
				}
				$var_1553=Db::table('ims_sudu8_page_shops_goods')->where('uniacid',$var_187)->count();
				$this->assign(goods,$var_1549);
				$this->assign('goodslist',$var_1550);
				$this->assign('counts',$var_1553);
			}
			else
			{
				$var_1554=Session::get('usergroup');
				if($var_1554==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_1554==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_1554==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(goods);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function goodsadd()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_1556=input('appletid');
				$var_1557=Db::table('applet')->where('id',$var_1556)->find();
				if(!$var_1557)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_1557);
				$var_1558=input('goodsid');
				$var_1559=Db::table('ims_sudu8_page_shops_shop')->where('uniacid',$var_1556)->order('num desc')->order('id desc')->select();
				$var_83='';
				if($var_1558)
				{
					$var_1560=DB::table('ims_sudu8_page_shops_goods')->where('uniacid',$var_1556)->where('id',$var_1558)->find();
					if($var_1560['images'])
					{
						$var_1560['images']=unserialize($var_1560['images']);
						if($var_1560['images'])
						{
							foreach($var_1560['images'] as $var_1561=>&$var_1562)
							{
								$var_1562=remote($var_1556,$var_1562,1);
							}
						}
					}
				}
				else
				{
					$var_1563=0;
					$var_1560='';
				}
				$this->assign('goodsid',$var_1558);
				$this->assign(goods,$var_1560);
				$this->assign('listAll',$var_1559);
			}
			else
			{
				$var_1564=Session::get('usergroup');
				if($var_1564==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_1564==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_1564==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(goodsadd);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function goodssave()
	{
		$var_1144=input('appletid');
		$var_1566=input('pid');
		$var_198=input('sid');
		$var_1567=input('flag');
		if(!$var_1567)
		{
			$var_1567=0;
		}
		$var_1568=input('hot');
		if(!$var_1568)
		{
			$var_1568=0;
		}
		$var_1569=Db::table('ims_sudu8_page_shops_shop')->where('uniacid',$var_1144)->where('id',$var_198)->find();
		if($var_1569)
		{
			$var_1570=array('uniacid' =>$var_1144,'sid' =>input('sid'),'num' =>input('num'),'flag' =>$var_1567,'hot' =>$var_1568,'title' =>input('title'),'buy_type' =>input('buy_type'),'pageview' =>input('pageview'),'vsales' =>input('vsales'),'rsales' =>input('rsales'),'sellprice' =>input('sellprice'),'marketprice' =>input('marketprice'),'storage' =>input('storage'),'descp' =>input('descp'));
		}
		$var_321=input('imgsrcs/a');
		if($var_321)
		{
			foreach($var_321 as $var_1571=>&$var_1572)
			{
				$var_1572=remote($var_1144,$var_1572,1);
			}
			$var_1570['images']=serialize($var_321);
		}
		else
		{
			$var_1570['images']=[];
		}
		$var_1573=input('commonuploadpic1');
		if($var_1573)
		{
			$var_1570['thumb']=remote($var_1144,$var_1573,1);
		}
		$var_1574=input('goodsid');
		if($var_1574)
		{
			$var_1575=Db::table('ims_sudu8_page_shops_goods')->where('uniacid',$var_1144)->where('id',$var_1574)->update($var_1570);
		}
		else
		{
			$var_1570['uniacid']=$var_1144;
			$var_1575=Db::table('ims_sudu8_page_shops_goods')->insert($var_1570);
		}
		if($var_1575)
		{
			$this->success('商品信息更新成功！',Url('Powerfulsh/goods').'?appletid='.$var_1144);
		}
		else
		{
			$this->error('商品信息更新失败没有修改项！');
		}
	}
	public function goodsdel()
	{
		$var_1577=input('appletid');
		$var_1578=input('goodsid');
		$var_18=array('uniacid'=>$var_1577,'id'=>$var_1578);
		$var_1579=Db::table('ims_sudu8_page_shops_goods')->where($var_18)->delete();
		if($var_1579)
		{
			$this->success('商品删除成功');
		}
		else
		{
			$this->success('商品删除失败');
		}
	}
	public function goodspass()
	{
		$var_1581=intval(input('goodsid'));
		$var_1582=input('appletid');
		$var_25=array('uniacid' =>$var_1582,'id' =>$var_1581,'status' =>1);
		$var_739=Db::table('ims_sudu8_page_shops_goods')->where('uniacid',$var_1582)->where('id',$var_1581)->update($var_25);
		if($var_739)
		{
			$this->success('审核通过');
		}
		else
		{
			$this->success('审核失败');
		}
	}
	public function goodscancel()
	{
		$var_545=intval(input('goodsid'));
		$var_1583=input('appletid');
		$var_1584=array('uniacid' =>$var_1583,'id' =>$var_545,'status' =>2);
		$var_1585=Db::table('ims_sudu8_page_shops_goods')->where('uniacid',$var_1583)->where('id',$var_545)->update($var_1584);
		if($var_1585)
		{
			$this->success('审核不通过');
		}
		else
		{
			$this->success('审核失败');
		}
	}
	public function order()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_1587=input('appletid');
				$var_1588=Db::table('applet')->where('id',$var_1587)->find();
				if(!$var_1588)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_1588);
				$var_243=input('op');
				if($var_243=='hx')
				{
					$var_1589=input('orderid');
					$var_1590=input('shopid');
					$var_1591['hxtime']=time();
					$var_1591['flag']=2;
					$var_1588=Db::table('ims_sudu8_page_duo_products_order')->where('id',$var_1589)->update($var_1591);
					if($var_1590!=0)
					{
						$var_1592=Db::table('ims_sudu8_page_shops_shop')->where('uniacid',$var_1587)->where('id',$var_1590)->field('tixian')->find()['tixian'];
						$var_1593=Db::table('ims_sudu8_page_duo_products_order')->where('uniacid',$var_1587)->where('id',$var_1589)->field('price')->find()['price'];
						$var_1592=$var_1592+$var_1593;
						$var_538=Db::table('ims_sudu8_page_shops_shop')->where('uniacid',$var_1587)->where('id',$var_1590)->update(array('tixian' =>$var_1592));
					}
					if($var_1588)
					{
						$this->success('核销成功');
					}
				}
				if($var_243=='fh')
				{
					$var_1589=input('orderid');
					$var_1591['flag']=2;
					$var_1588=Db::table('ims_sudu8_page_duo_products_order')->where('id',$var_1589)->update($var_1591);
					if($var_1588)
					{
						$this->success('操作成功');
					}
				}
				if($var_243==fahuo)
				{
					$var_1589=input('orderid');
					$var_1591['hxtime']=time();
					$var_1591['kuadi']=input('kuadi');
					$var_1591['kuaidihao']=input('kuaidihao');
					$var_1591['flag']=4;
					$var_1588=Db::table('ims_sudu8_page_duo_products_order')->where('id',$var_1589)->update($var_1591);
					if($var_1588)
					{
						$this->success('发货成功');
					}
				}
				$var_1594=Db::table('ims_sudu8_page_duo_products_order')->where('uniacid',$var_1587)->where('sid','neq',0)->order('creattime desc')->paginate(10,false,['query' =>array('appletid'=>input('appletid'))]);
				$var_760=$var_1594->toArray()['data'];
				foreach($var_760 as $var_1595=>&$var_1588)
				{
					$var_1588['jsondata']=unserialize($var_1588['jsondata']);
					$var_1588['creattime']=date('Y-m-d H:i:s',$var_1588['creattime']);
					$var_1588['hxtime']=$var_1588['hxtime']==0?'未核销':date('Y-m-d H:i:s',$var_1588['hxtime']);
					$var_1588['userinfo']=Db::table('ims_sudu8_page_user')->where('uniacid',$var_1587)->where('openid',$var_1588['openid'])->find();
					$var_1588['counts']=count($var_1588['jsondata']);
					$var_1596=Db::table('ims_sudu8_page_coupon_user')->where('uniacid',$var_1587)->where('id',$var_1588['coupon'])->find();
					$var_1597=Db::table('ims_sudu8_page_coupon')->where('uniacid',$var_1587)->where('id',$var_1596['cid'])->find();
					$var_1588['couponinfo']=$var_1597;
					if($var_1588['sid']==0)
					{
						$var_1588['shopname']='总平台';
					}
					else
					{
						$var_1588['shopname']=Db::table('ims_sudu8_page_shops_shop')->where('uniacid',$var_1587)->where('id',$var_1588['sid'])->field('name')->find()['name'];
					}
					$var_1598=0;
					foreach($var_1588['jsondata'] as $var_1599=>&$var_1600)
					{
						$var_1598+=($var_1600['num']*1)*($var_1600['proinfo']['price']);
					}
					$var_1588['allprice']=$var_1598;
					$var_707=Db::table('ims_sudu8_page_rechargeconf')->where('uniacid',$var_1587)->find();
					if(!$var_707)
					{
						$var_486=10000;
						$var_1601=1;
					}
					else
					{
						$var_486=$var_707['score'];
						$var_1601=$var_707['money'];
					}
					$var_1588['jfmoney']=$var_1588['jf']*$var_1601/$var_486;
					if($var_1588['address']!=0)
					{
						$var_1588['address_get']=Db::table('ims_sudu8_page_duo_products_address')->where('openid',$var_1588['openid'])->where('id',$var_1588['address'])->find();
					}
					else
					{
						$var_1588['address_get']=unserialize($var_1588['m_address']);
					}
					if($var_1588['formid'])
					{
						$var_1588['formcon']=Db::table('ims_sudu8_page_formcon')->where('uniacid',$var_1587)->where('id',$var_1588['formid'])->find();
						$var_1588['formcon']=unserialize($var_1588['formcon']['val']);
						foreach($var_1588['formcon'] as $var_1602=>$var_1603)
						{
							if($var_1603['z_val'])
							{
								foreach($var_1603['z_val'] as $var_1604=>$var_1605)
								{
									if(strpos($var_1605,'http')===false)
									{
										$var_1588['formcon'][$var_1602]['z_val'][$var_1604]=remote($var_1587,$var_1605,1);
									}
									else
									{
										$var_1588['formcon'][$var_1602]['z_val'][$var_1604]=$var_1605;
									}
								}
							}
						}
					}
				}
				$this->assign('orders',$var_760);
				$this->assign('total',$var_1594);
			}
			else
			{
				$var_1606=Session::get('usergroup');
				if($var_1606==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_1606==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_1606==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(order);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function fahuo()
	{
		$var_1608=input('appletid');
		$var_1609=input('orderid');
		$var_554=input('shopid');
		$var_1610['hxtime']=time();
		$var_1610['flag']=2;
		Db::table('ims_sudu8_page_duo_products_order')->where('uniacid',$var_1608)->where('id',$var_1609)->update($var_1610);
		if($var_554!=0)
		{
			$var_1611=Db::table('ims_sudu8_page_shops_shop')->where('uniacid',$var_1608)->where('id',$var_554)->find()['tixian'];
			$var_1612=Db::table('ims_sudu8_page_duo_products_order')->where('uniacid',$var_1608)->where('id',$var_1609)->find()['price'];
			$var_1611=$var_1611+$var_1612;
			$var_1613=Db::table('ims_sudu8_page_shops_shop')->where('uniacid',$var_1608)->where('id',$var_554)->update(array('tixian' =>$var_1611));
		}
		if($var_1613)
		{
			$this->success('核销成功');
		}
	}
	public function withdraw()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_1134=input('appletid');
				$var_1615=Db::table('applet')->where('id',$var_1134)->find();
				if(!$var_1615)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_1615);
				$var_1616=Db::table('ims_sudu8_page_shops_tixian')->where('uniacid',$var_1134)->order('createtime desc')->select();
				foreach($var_1616 as $var_1617=>&$var_1618)
				{
					$var_1618['shopname']=Db::table('ims-sudu8_page_shops_shop')->where("$var_1619",$var_1134)->where('id',$var_1618['sid'])->find()['name'];
				}
				;
				$var_1620=Db::table('ims_sudu8_page_shops_tixian')->where('uniacid',$var_1134)->count();
				$this->assign('records',$var_1616);
				$this->assign('counts',$var_1620);
			}
			else
			{
				$var_1621=Session::get('usergroup');
				if($var_1621==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_1621==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_1621==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(withdraw);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function withdrawpass()
	{
		$var_1623=input('appletid');
		$var_1624=input('id');
		$var_1625=array('flag' =>1);
		$var_1626=Db::table('ims_sudu8_page_shops_tixian')->where('uniacid',$var_1623)->where('id',$var_1624)->update($var_1625);
		if($var_1626)
		{
			$this->success('审核成功');
		}
	}
	public function system()
	{
		if(check_login())
		{
			if(powerget())
			{
				$var_100=input('appletid');
				$var_1627=Db::table('applet')->where('id',$var_100)->find();
				if(!$var_1627)
				{
					$this->error('找不到对应的小程序！');
				}
				$this->assign('applet',$var_1627);
				$var_1628=Db::table('ims_sudu8_page_shops_set')->where('uniacid',$var_100)->find();
				if($var_1628['bg'])
				{
					$var_1628['bg']=remote($var_100,$var_1628['bg'],1);
				}
				$this->assign('systems',$var_1628);
			}
			else
			{
				$var_1629=Session::get('usergroup');
				if($var_1629==1)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/applet');
				}
				if($var_1629==2)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
				if($var_1629==3)
				{
					$this->error('您没有权限操作该小程序或找不到相应小程序！','Applet/index');
				}
			}
			return $this->fetch(system);
		}
		else
		{
			$this->redirect('Login/index');
		}
	}
	public function systemsave()
	{
		$var_1631=input('appletid');
		$var_1632=Db::table('ims_sudu8_page_shops_set')->where('uniacid',$var_1631)->find();
		$var_274=array();
		$var_1633=input('tjnum');
		if($var_1633)
		{
			$var_274['tjnum']=$var_1633;
		}
		else
		{
			$var_274['tjnum']=6;
		}
		$var_1634=input('num');
		if($var_1634)
		{
			$var_274['num']=$var_1634;
		}
		else
		{
			$var_274['num']=6;
		}
		$var_1635=$_POST['apply'];
		if($var_1635)
		{
			$var_274['apply']=$var_1635;
		}
		$var_1636=$_POST[goods];
		if($var_1636)
		{
			$var_274[goods]=$var_1636;
		}
		$var_1637=$_POST[withdraw];
		if($var_1637)
		{
			$var_274[withdraw]=$var_1637;
		}
		$var_1638=input('minimum');
		if($var_1638)
		{
			$var_274['minimum']=$var_1638;
		}
		$var_1639=input('commonuploadpic1');
		if($var_1639)
		{
			$var_274['bg']=remote($var_1631,$var_1639,2);
		}
		$var_274['protocol']=input('protocol');
		$var_1640=Db::table('ims_sudu8_page_shops_set')->where('uniacid',$var_1631)->count();
		if($var_1640>0)
		{
			$var_1632=Db::table('ims_sudu8_page_shops_set')->where('uniacid',$var_1631)->update($var_274);
		}
		else
		{
			$var_274['uniacid']=$var_1631;
			$var_1632=Db::table('ims_sudu8_page_shops_set')->insert($var_274);
		}
		if($var_1632)
		{
			$this->success('基础信息更新成功！');
		}
		else
		{
			$this->error('基础信息更新失败，没有修改项！');
			$this->redirect('Login/index');
		}
	}
	function onepic_uploade($v_1)
	{
		$var_1641=request()->file($v_1);
		if(isset($var_1641))
		{
			$var_1642=upload_img();
			$var_1643=$var_1641->validate(['ext'=>'jpg,png,gif,jpeg'])->move($var_1642);
			if($var_1643)
			{
				$var_1644=ROOT_HOST.'/upimages/'.date('Ymd',time()).'/'.$var_1643->getFilename();
				return $var_1644;
			}
		}
	}
	public function imgupload()
	{
		$var_1646['appletid']=$_GET['appletid'];
		$var_1647=request()->file('');
		foreach($var_1647 as $var_1648)
		{
			$var_1649=$var_1648->validate(['ext'=>'jpg,png,gif,jpeg'])->move(ROOT_PATH.'public' .DS.'upimages');
			if($var_1649)
			{
				$var_1646['url']=ROOT_HOST.'/upimages/'.date('Ymd',time()).'/'.$var_1649->getFilename();
				$var_1646['dateline']=time();
				$var_1650=Db::table('ims_sudu8_page_shops_shop')->insert($var_1646);
			}
			else
			{
				return $this->error($var_1648->getError());
			}
		}
	}
	public function getimg()
	{
		$v_2=$_POST['id'];
		$var_1652=Db::table('ims_sudu8_page_shops_shop')->where('appletid',$v_2)->select();
		if($var_1652)
		{
			return $var_1652;
		}
	}
	public function del()
	{
		$var_1654=input('id');
		$var_1655=Db::table('ims_sudu8_page_shops_shop')->where('id',$var_1654)->delete();
		if($var_1655)
		{
			return 1;
		}
		else
		{
			$this->error('删除失败！');
		}
	}
}
?>