layui.use("layer",function(){layer_photos()});malert=function(a,b,c,d,e){layer.open({content:a,skin:d||!1,btn:b||!1,time:c||0,yes:function(a){layer.close(a)}})};released=function(a){layer.load();$.get("/html/released",{type:a},function(a){layer_ly(a,!1,!0,"560px","auto")})};sign=function(){Aform("sign","",function(a){if(-2==a.state)return layer_lp("\u7b7e\u5230","login_sign"),!1;Rs(a)})};
layer_lp=function(a,b){layer.confirm('\u4eb2\uff0c\u60a8\u9700\u8981\u5148<font color="red">\u767b\u9646</font>\u624d\u80fd<font color="#ff6600">'+a+"</font>\u54e6\uff01",{icon:0,btn:["\u53bb\u767b\u9646","\u6253\u9171\u6cb9"]},function(){layer.closeAll();layer_login("\u518d"+a,b)},function(){layer.msg("\u597d\u5427\uff0c\u4eb2\uff0c\u90a3\u60a8\u5c31\u7ee7\u7eed\u6253\u9171\u6cb9\u5427\uff01")})};
var login=function(a){var b=$("#popup-captcha");a.onSuccess(function(){var c=a.getValidate(),d=$("input[name=login_name]").val(),e=$("input[name=login_pass]").val();Aform("login","mode=1&login_name="+d+"&login_pass="+e+"&geetest_challenge="+c.geetest_challenge+"&geetest_validate="+c.geetest_validate+"&geetest_seccode="+c.geetest_seccode,function(c){if(1!=c.state)return b.hide(),a.reset(),Rs(c),!1;UCheck()})});$("#login_submit_button").click(function(){var c=$("input[name=login_name]"),d=$("input[name=login_pass]");
if(!judge(c.val()))return layer.tips("\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u5e10\u53f7(\u90ae\u7bb1)",c),!1;if(6>d.val().length)return layer.tips("\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u5bc6\u7801(6-20\u4f4d)",d),!1;if(b.is(":visible")&&!a.getValidate())return layer.tips("\u8bf7\u5148\u5b8c\u6210\u9a8c\u8bc1",b),!1;b.show()});a.appendTo(b)};
function logingt(){$.getScript("https://static.geetest.com/static/tools/gt.js",function(){$.ajax({url:"/html/StartCaptchaServlet?t="+(new Date).getTime(),type:"get",dataType:"json",success:function(a){initGeetest({gt:a.gt,width:"100%",challenge:a.challenge,new_captcha:a.new_captcha,product:"popup",offline:!a.success},login)}})})}
layer_login=function(a,b){a=a||!1;$.get("/html/login?c="+(b||""),function(b){layer.closeAll("loading");title=a?"\u4eb2\uff01\u5148\u767b\u4e2a\u5f55"+a:"\u8d26\u53f7\u767b\u9646";layer.open({type:1,title:[title,"border:none; background:#f2f2f2; color:#333;font-size:14px;"],shadeClose:!0,shade:[.1,"#000"],area:["400px"],content:b,success:function(){logingt()}})})};
function UCheck(a){a=a||"ajax_login";0<$('input[name="ureturn"]').length?(a=$.trim($('input[name="ureturn"]').val()),CheckHzurl(a)?window.location.href=a:window.location.reload()):0<$('input[name="uclick"]').length?(a=$('input[name="uclick"]').val().split("|"),"click"==$.trim(a[0])&&$($.trim(a[1])).trigger("click")):0<$(".top_box").length&&Aform(a,"",function(a){1==a.state?$.each(a,function(a,b){0<$("."+a).length&&$("."+a).html(b)}):Rs(a)});layer.closeAll("page")}
function deling(a){uploader.removeFile(a);$("#file-"+a).remove();0>=$("#FileListing tr").length?$("#pluing").hide():$("#pluing u").html(uploader.files.length)}function budget(){var a=$("input[name=money]").val(),b=$("input[name=role]:checked").val(),c=$("input[name=fees]:checked").val();b&&a&&c?(b=.02*a,$("#budget").show(),"buy"==c?($("#bm").html(1*a+1*b),$("#sm").html(a)):"sell"==c?($("#bm").html(a),$("#sm").html(a-b)):($("#bm").html(1*a+.5*b),$("#sm").html(a-.5*b))):$("#budget").hide()}
function verify(a){var b=$("input[name=vcode]").val();if("phone"==a&&4!=b.length||"email"==a&&6!=b.length)return $("input[name=vcode]").val(""),$("input[name=vcode]").focus(),layer.tips("\u9a8c\u8bc1\u7801\u9519\u8bef\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165",$("input[name=vcode]")),!1;"phone"!=a&&"email"!=a||Aform("verify",$("form *[value!='']").serialize()+"&mode="+a)}
sendbtn=function(a,b){var c=$(a).attr("data");if(!judge($("input[name="+c+"]").val(),c))return layer.tips($("input[name="+c+"]").attr("placeholder"),$("input[name="+c+"]"),{tips:[3,"#f90"]}),$("input[name="+c+"]").focus(),!1;$(a).attr("disabled",!0);Aform("sendinfo",$("form").serialize(),function(c){-1==c.state?sendtime(a,b):$(a).attr("disabled",!1);Rs(c)})};
sendtime=function(a,b){function c(b){return function(){if(b==d)$(a).removeClass("layui-btn-disabled"),$(a).val("\u53d1\u9001\u9a8c\u8bc1\u7801"),$(a).attr("disabled",!1);else{var c=d-b;$(a).val(c+"\u79d2\u540e\u53ef\u4ee5\u91cd\u53d1")}}}var d=b||60;$(a).attr("disabled",!0);$(a).val(d+"\u79d2\u540e\u53ef\u4ee5\u91cd\u53d1").addClass("layui-btn-disabled");for(b=1;b<=d;b++)setTimeout(c(b),1E3*b)};$(".pingfen_btn").live("hover",function(a){"mouseenter"==a.type?$(this).addClass("active"):$(this).removeClass("active")});
$(".uim p,.uim a").live("click",function(){var a=$(this),b="",c=a.closest("span"),d=a.parents(),e=c.attr("uinfo").split("|");layer.load();a.siblings().each(function(){b+=$(this).html()+","});$.get("/html/contact",{cim:a.html(),im:b,type:d.attr("class")},function(a){layer_ly(a,'<img src="'+e[1]+'" style="width:20px;height:20px;margin-left:-10px;float:left;margin-top:10px;padding:1px;border: 1px solid #ddd;"><strong style="float:left;max-width:130px;overflow:hidden;color:#ff6600;padding:0 5px;">'+e[0]+
'</strong> <span style="color:#666;float:left;">'+d.attr("title")+"</span>",!0,"330px")})});
$(document).ready(function(){function a(a){b&&($(a).hide(),$(".toggle_center").removeClass("mcur"))}$.isFunction($.fn.tipso)&&$(".tips").tipso();$(".checkLen").each(function(){CheckLen(this,parseInt($(this).attr("d_len")))});updateEndTime();$(".tablelist:not(.noodd) tbody tr:odd,.imgtable tbody tr:odd").addClass("odd");$("#ly_browse").click(function(){layer_iframe("html/browse","\u6700\u8fd1\u6d4f\u89c8\u8bb0\u5f55","800px","430px")});$("#ly_kfqq").click(function(){$.get("/html/csc",function(a){layer_ly(a,
"\u7ba1\u7406\u5ba2\u670d",!0,"390px")})});0<$(".c_r_des").length?($(".c_r_des").find("img").each(function(){if(900<parseInt($(this).width())){var a=$(this).width(),a=900*($(this).height()/a);$(this).width(900);$(this).height(a)}}),0<$(".c_r_des img").length&&layer_photos(".c_r_des"),gelist(),$().layer_top()):0<$("input[name=selist]").length&&selist();0<$(".adsbygoogle").length&&loadScript("//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js");0<$("#ly_gotop").length&&($(window).scroll(function(a){h=$(window).height();t=$(document).scrollTop();
t>h?$("#ly_gotop").show():$("#ly_gotop").hide()}),$("#ly_gotop").click(function(){$("html,body").animate({scrollTop:0},300)}));$(".searchtype").click(function(){$(".searchlist").toggle()});$(".searchlist li").click(function(){$(".searchtype").html($(this).html());$(this).addClass("cur").siblings().removeClass("cur");$(".searchlist").hide()});$(".searchbtn").click(function(){var a=$(".searchval");if(""==a.val().replace(/\s/,""))return layer.alert("\u8bf7\u8f93\u5165\u641c\u7d22\u5173\u952e\u8bcd",
{icon:0},function(b){a.focus();layer.close(b)}),!1;var b=$(".searchlist .cur").attr("data");location.href="code"==b||"serve"==b||"shop"==b?"/"+b+"/key/"+a.val():"//"+b+".huzhan.com/key/"+a.val()});$(".imfav").click(function(){var a=$(this).attr("id");Aform("fav","info="+$(this).attr("info"),function(b){if(-2==b.state)return layer_lp("\u6536\u85cf",a),!1;Rs(b)})});var b=!1;$(".toggle_center").hover(function(){$(this).parent().next().show();$(this).addClass("mcur");b=!1},function(){$this=$(this).parent().next();
b=!0;window.clearTimeout(c);var c=window.setTimeout(function(){a($this)},300)});$(".toggle_pop,.rev_pop").hover(function(){b=!1},function(){$this=$(this);b=!0;window.clearTimeout(c);var c=window.setTimeout(function(){a($this)},300)});$(".top_box li:not(.not)").live({mouseenter:function(){$(this).addClass("curr")},mouseleave:function(){$(this).removeClass("curr")}});$(".w_d_list .l2,.w_list .l2").hover(function(){var a=$(this);item1Timer=setTimeout(function(){$(a).children("span").show().animate({top:0,
height:"100%"},300)},100)},function(){var a=$(this);clearTimeout(item1Timer);$(a).children("span").animate({top:"50%",height:0},300,function(){$(a).children("span").hide()})})});$(".Search-inp").live("keypress",function(a){13==(a.keyCode?a.keyCode:a.which?a.which:a.charCode)&&$(this).closest(".Search-box").find(".Search-btn").click()});$(".o_number").live("keyup",function(){var a=$(this).val();$(this).val(a.replace(/\D|^0/g,""))});$(".checkLen").live("keyup",function(){CheckLen(this,parseInt($(this).attr("d_len")))});
$(".installing").live("click",function(){$.get("/html/installing?"+attArr(this),function(a){layer_ly(a,"\u5b89\u88c5\u670d\u52a1\u8be6\u60c5",!0,"600px")})});$(".preview").live("click",function(){layer_iframe("html/preview/"+$("input[name=good]").val()+"/"+$("input[name=action]").val()," ","880px","510px")});
$(".serve_btn").live("click",function(){layer.load();var a=$(this),b="undefined"==typeof $(this).attr("number")?readmeta("Or-Number"):$(this).attr("number");$Me=$(".Edition a.cur");Aform("u","",function(c){if(-2==c.state)return layer_login("\u8d2d\u4e70","."+a.attr("class")),!1;$.post("/deal/addserve",{number:b,money:parseInt($Me.attr("data")),edition:$Me.attr("title"),piece:$("#p_number").val()},function(a){layer_ly(a,"\u670d\u52a1\u4e0b\u5355",!1,"700px")})})});
$(".allmoney").live("click",function(){$.post("/html/allmoney",{number:$(this).attr("number")},function(a){layer_ly(a,!1,!0,"650px","","",!0)})});$(".Edition a").live("click",function(){var a=$(this).closest("div").find(".price_m"),b=$(this).closest("div").find(".Price_range");$(this).hasClass("cur")?(a.html(b.html()),$(this).removeClass("cur")):(a.html($(this).attr("data")),$(this).addClass("cur").siblings("a").removeClass("cur"))});
$(".addred").live("click",function(){var a=$(this).siblings("#addred_num"),b=1;"-"==$(this).val()&&(b=-1);b=parseInt(a.val())+b;if("day"==a.attr("data")){if(0>=b||60<b)return layer.alert("\u4ea4\u6613\u5468\u671f\uff0c\u4e0d\u80fd\u5c0f\u4e8e1\u5929\u6216\u5927\u4e8e60\u5929",{icon:2}),!1}else if("piece"==a.attr("data")){if(0>=b)return layer.alert("\u8d2d\u4e70\u6570\u91cf\u4e0d\u80fd\u5c0f\u4e8e1\u4ef6",{icon:2}),!1;$(".ly_total").html(toDecimal2(parseInt($(".ly_money").html())*b))}a.val(b)});
$(".see_stats").live("click",function(){$.get("/html/stats",{number:$(this).attr("id")},function(a){layer_ly(a,"\u7f51\u7ad9\u7edf\u8ba1\u8be6\u60c5",!0,"652px")})});$(".login_click").live("click",function(){var a=$(this).attr("id");if("qq"==a||"baidu"==a)var b=720,c=420;else b="sina"==a?770:570,c=530;openwindow("https://www.zhisu.com/"+a,$(this).attr("title"),b,c)});
function openwindow(a,b,c,d){window.open(a,b,"height="+d+",,innerHeight="+d+",width="+c+",innerWidth="+c+",top="+(window.screen.availHeight-30-d)/2+",left="+(window.screen.availWidth-10-c)/2+",toolbar=no,menubar=no,scrollbars=auto,resizable=yes,location=yes,status=no")}function replace_html(a){a=a.replace(/<img[^>]*>/ig,"");a=a.replace(/<a[^>]*>/ig,"");return a=a.replace(/<\/a>/ig,"")}
function CheckLen(a,b){var c=$(a).val().replace(/[, ]/g,"");myinfo=getStrleng(c,b);myinfo[0]>2*b?($(a).val(c.substring(0,myinfo[1]-1)),$count=0):$count=Math.floor((2*b-myinfo[0])/2);$check_tisp=$(a).parent().siblings("#check_count");0>=$check_tisp.length&&($check_tisp=$(a).parent().parent().find("#check_count"));$check_tisp.html($count);}
function getStrleng(a,b){for(i=myLen=0;i<a.length&&myLen<=2*b;i++)0<a.charCodeAt(i)&&128>a.charCodeAt(i)?myLen++:myLen+=2;return[myLen,i]}
function judge(a,b){return("phone"==b?/^0?1[3|4|5|7|8][0-9]\d{8}$/:"tel"==b?/^(?:(?:0\d{2,3})-)?(?:\d{7,8})(-(?:\d{3,}))?$/:"domain"==b?/^([\w-]+\.)+((com)|(cn)|(com\.cn)|(net)|(net\.cn)|(org)|(org\.cn)|(ac)|(ac\.cn)|(asia)|(audio)|(band)|(bid)|(bike)|(biz)|(blue)|(club)|(cab)|(camp)|(care)|(cash)|(cc)|(cheap)|(city)|(click)|(cloud)|(club)|(cn\.com)|(co)|(com\.hk)|(com\.tw)|(cool)|(date)|(design)|(download)|(email)|(engineer)|(eu)|(fail)|(farm)|(fish)|(flowers)|(fund)|(game)|(games)|(gift)|(gov\.cn)|(green)|(guide)|(guru)|(help)|(hiphop)|(hk)|(host)|(hosting)|(house)|(in)|(info)|(ink)|(io)|(it)|(jp)|(kim)|(la)|(land)|(lawyer)|(life)|(limo)|(link)|(live)|(loan)|(lol)|(ltd)|(ltd\.uk)|(market)|(me)|(me\.uk)|(media)|(mobi)|(mom)|(name)|(news)|(ninja)|(onLine)|(online)|(org\.uk)|(party)|(photo)|(pics)|(pink)|(plc\.uk)|(poker)|(press)|(pro)|(pub)|(pw)|(red)|(ren)|(rocks)|(science)|(sexy)|(sg)|(sh)|(shoes)|(shop)|(site)|(so)|(social)|(software)|(solar)|(space)|(store)|(studio)|(tax)|(tech)|(tips)|(tm)|(today)|(tools)|(top)|(town)|(toys)|(trade)|(travel)|(tv)|(tw)|(us)|(vc)|(video)|(vip)|(wang)|(watch)|(website)|(wiki)|(win)|(work)|(ws)|(xin)|(xyz)|(gg)|(zone)|(\u4e2d\u56fd)|(\u4fe1\u606f)|(\u516c\u53f8)|(\u5728\u7ebf)|(\u79fb\u52a8)|(\u7f51\u5740)|(\u7f51\u5e97)|(\u7f51\u7edc))$/:/^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+((\.[a-zA-Z0-9_-]{2,3}){1,2})$/).test(a)?
!0:!1}function filterStr(a){100<a.length&&(a=a.substring(0,100));for(var b=/[`~!@#$^&*()=|{}':;',\[\].<>/?~\uff01@#\uffe5\u2026\u2026&*\uff08\uff09\u2014\u2014|{}\u3010\u3011\u2018\uff1b\uff1a\u201d\u201c'\u3002\uff0c\u3001\uff1f%+_]/,c="",d=0;d<a.length;d++)c+=a.substr(d,1).replace(b,"");return c}function readmeta(a){return $("meta[name="+a+"]").attr("content")}layer_photos=function(a){a=a||".bfiles";0<$(a).length&&setTimeout(function(){layer.photos({photos:a,shift:5})},100)};
Aform=function(a,b,c,d){$.ajax({type:"POST",url:"/Aform/index/"+a,async:d||!1,data:b,dataType:"json",success:function(a){c?c(a):Rs(a)},error:function(){layer.closeAll("loading");layer.msg("\u7f51\u7edc\u5f02\u5e38\uff0c\u8bf7\u91cd\u8bd5\uff01");return!1}})};dform=function(a,b,c){$.ajax({type:"POST",url:"/Dform/"+b,async:!0,data:a,dataType:"json",success:function(a){c?c(a):Rs(a)},error:function(){layer.closeAll("loading");layer.msg("\u7f51\u7edc\u5f02\u5e38\uff0c\u8bf7\u91cd\u8bd5\uff01");return!1}})};
Rs=function(a){layer.closeAll("loading");switch(a.state){case -1:layer.tips(a.info,a.element,{tips:[a.tips||1,a.color||"#f90"],time:a.time||4E3});$(a.element).val("").focus();a.fun&&eval(a.fun);break;case -2:layer.confirm(a.info||"\u767b\u5f55\u5931\u6548\uff0c\u8bf7\u91cd\u65b0\u767b\u5f55\uff01",{icon:a.icon||8,btn:[a.btn1||"\u767b\u9646",a.btn2||"\u53d6\u6d88"]},function(b){a.url?location.href=a.url:layer_login();layer.close(b)},function(a){layer.close(a)});a.fun&&eval(a.fun);break;case -3:a.fun&&
eval(a.fun);break;case 301:location.href=a.url;break;default:a.clear||layer.alert(a.info,{icon:a.state},function(b){a.fun?eval(a.fun)+layer.close(b):a.url?1==a.url?location.reload():location.href=a.url:a.element?$(a.element).val("").focus()+layer.close(b):layer.close(b)})}};layer_ly=function(a,b,c,d,e){layer.open({type:1,title:b,closeBtn:1,shade:[.05,"#000"],area:[d||"auto",e||"auto"],shadeClose:c||!1,content:a});layer.closeAll("loading")};
layer_iframe=function(a,b,c,d,e,k){d=d||"100px";layer.open({type:2,title:b,shadeClose:k?!0:!1,shade:[.05,"#000"],area:[c,d],content:["/"+a,e||"no"],success:function(a,b){"100px"==d&&window[a.find("iframe")[0].name].iframeautos(b)}})};
function iframeautos(a){$height=$(document).height()+44;$height>$(window.parent.window).height()&&($height=parseInt(.9*$(window.parent.window).height()));$top=($(window.parent.window).height()-$height)/2+"px";parent.layer.iframeAuto(a);parent.layer.style(a,{height:$height+"px",top:$top})}Player_alert=function(a,b,c){layer.closeAll();layer.alert(a,{icon:b},function(a){1==c?location.reload():0==c?layer.close(a):window.location.href=c})};
function attArr(a){a=a.attributes;for(var b=[],c=0;c<a.length;c++)b.push(a[c].name+"="+a[c].nodeValue.replace(/[~'!<>@#$%^&*()-+_=:]/g,""));
return b.join("&")}function loadScript(a){var b=document.createElement("script");b.type="text/javascript";b.src=a;document.body.appendChild(b)}
list=function(a){a=a||0;var b=layer.load();1<a?scTop(".mwz"):"R"==a&&(a=parseInt($(".ohave").html())||0,a+="&Rf=1");$.ajax({type:"POST",url:"/Apage/",async:!0,data:$("form *[value!='']").serialize()+"&page="+a,dataType:"json",success:function(a){if(-2==a.state)return Rs(a),!1;$.each(a,function(a,b){$("."+a).empty();$("."+a).html(b)});Cxchange();layer.close(b)},error:function(){layer.msg("\u7f51\u7edc\u5f02\u5e38\uff0c\u8bf7\u91cd\u8bd5\uff01");layer.close(b);return!1}})};
$(".message_a").live("click",function(){$(this).removeClass("message_a");bulk("batch=message_read&id="+$(this).attr("data_id"))});function message_operate(a,b,c,d){var e=getFormJson();e.action=$(a).attr("action");e.batch=c||e.batch;e.scene=d||0;if(0!=b){if(void 0===e.C1)return layer.alert("\u81f3\u5c11\u9009\u62e9\u4e00\u6761\u64cd\u4f5c\u5bf9\u8c61",{icon:5}),!1}else e.all=1;bulk(e)}
function bulk(a){$.ajax({type:"POST",url:"/execute/routine/",async:!1,data:a,dataType:"json",success:function(a){Rs(a);return!1},error:function(){layer.msg("\u7f51\u7edc\u5f02\u5e38\uff0c\u8bf7\u91cd\u8bd5");return!1}})}
$(".cart_delete").live("click",function(){var a=$(this),b=a.attr("number"),c="undefined"==typeof $(this).attr("mode")?0:1;Aform("cart_delete","&number="+b+"&mode="+c,function(b){if(1==c){var d=a.closest("dl");(1<d.children("ul").length?a.closest("ul"):d).slideUp(500,function(){$(this).remove();carmoney()})}else $.each(b,function(a,b){0<$("."+a).length&&$("."+a).html(b)}),a.closest("dd").slideUp(500,function(){$(this).remove()}),"undefined"!=typeof b.cart_data&&$(".top_cart").slideDown(500,function(){$(".top_cart dt").remove();
$(this).append(b.cart_data)});Rs(b)})});$(".cart_empty").live("click",function(){var a=$(this),b="undefined"==typeof $(this).attr("mode")?0:1;layer.confirm("\u786e\u5b9a\u8981<strong style='color:red'>\u6e05\u7a7a\u8d2d\u7269\u8f66</strong>\u5417\uff1f",{icon:3},function(c){Aform("cart_empty","&mode="+b,function(d){1==d.state&&($.each(d,function(a,b){0<$("."+a).length&&$("."+a).html(b)}),1==b?carmoney()+a.remove():layer.msg("\u8d2d\u7269\u8f66\u5df2\u6e05\u7a7a\uff01",{offset:"t",icon:1}));layer.close(c)})})});
function updateEndTime(){var a=(new Date).getTime();$(".ttime").each(function(b){b=this.getAttribute("endTime");var c=(eval("new Date("+b.replace(/\d+(?=-[^-]+$)/,function(a){return parseInt(a,10)-1}).match(/\d+/g)+")").getTime()-a)/1E3;if(0<c){b=Math.floor(c%60);var d=Math.floor(c/60%60),e=Math.floor(c/3600%24),c=Math.floor(c/3600/24);$(this).html(c+"\u5929"+e+"\u5c0f\u65f6"+d+"\u5206"+b+"\u79d2")}else $(this).html("\u5df1\u7ed3\u675f")});setTimeout("updateEndTime()",1E3)}
function toDecimal2(a){var b=parseFloat(a);if(isNaN(b))return!1;b=Math.round(100*a)/100;a=b.toString();b=a.indexOf(".");0>b&&(b=a.length,a+=".");for(;a.length<=b+2;)a+="0";return a}function ifstr(a,b){return rs=-1!=a.indexOf(b)?!0:!1}function CheckHzurl(a){var b=RegExp();b.compile("^(http|https)://[A-Za-z0-9]{1,8}.huzhan.com?[A-Za-z0-9-_%&?/.=]+$");return b.test(a)?!0:!1}
function getFormJson(a){var b={};a=$(a||"form *[value!='']").serializeArray();$.each(a,function(){void 0!==b[this.name]?(b[this.name].push||(b[this.name]=[b[this.name]]),b[this.name].push(this.value||"")):b[this.name]=this.value||""});return b}
function usize(a){a=a.toLowerCase();-1==a.indexOf("b")&&(a+="b");/[0-9]*[a-z]b/.test(a)||-1==a.indexOf("b")||(a=a.substring(0,a.indexOf("b")),a=Math.ceil(a/1024)+"kb");-1!=a.indexOf("kb")&&5<a.length&&(a=a.substring(0,a.indexOf("kb")),a=Math.ceil(a/1024)+"mb");-1!=a.indexOf("mb")&&5<a.length&&(a=a.substring(0,a.indexOf("mb")),a=Math.ceil(a/1024)+"gb");-1!=a.indexOf("gb")&&5<a.length&&(a=a.substring(0,a.indexOf("gb")),a=Math.ceil(a/1024)+"tb");return a}
progress=function(a){layer.closeAll("loading");$("form").keypress(function(a){if(13==a.which)return!1});0==$("#progress").length&&$("body").append('<div id="progress"><span id="progress-bar" ><span id="progress-in" style="width:1%"></span></span><br><span id=\'progress-tisp\'>\u6b63\u5728\u4e0a\u4f20\u6570\u636e\uff08<span id="progress-upload">1</span>/<span id="progress-uploaded">0</span>\uff09\uff0c\u8bf7\u7a0d\u7b49\u2026</span><ul><strong>\u56de\u6267\u4fe1\u606f\uff1a</strong></ul></div>');layer.open({type:1,
shade:[.02,"#000"],title:!1,closeBtn:0,content:$("#progress")});if(a)return $("#progress-tisp").html("\u6570\u636e\u6b63\u5728\u63d0\u4ea4\u4e2d\uff0c\u8bf7\u7a0d\u7b49\u2026"),$("#progress-in").width("100%"),!1};function scTop(a,b){b||(b=0);$("html, body").animate({scrollTop:$(a).offset().top-b},800)}
function Cxchange(){0<$(":checkbox[name=C1]:not(:disabled):not(:checked)").length||0>=$(":checkbox[name=C1]:not(:disabled)").length?Cchange($(":checkbox[name=xuan]"),!1):Cchange($(":checkbox[name=xuan]"),!0)}function Cchange(a,b){a.attr("checked",b);"undefined"!==typeof form&&form.render("checkbox")}
(function(a){a.fn.extend({Scroll:function(b,c){b||(b={});var d=a("#"+b.up),e=a("#"+b.down),k,f=this.eq(0).find("ul:first");c=f.find("li:first").height()+5;var g=b.line?parseInt(b.line,10):parseInt(this.height()/c,10),n=b.speed?parseInt(b.speed,10):3E3;timer=b.timer;0==g&&(g=1);var p=0-g*c,l=function(){d.unbind("click",l);f.animate({marginTop:p},n,function(){for(i=1;i<=g;i++)f.find("li:first").appendTo(f);f.css({marginTop:0});d.bind("click",l)})},m=function(){e.unbind("click",m);for(i=1;i<=g;i++)f.find("li:last").show().prependTo(f);
f.css({marginTop:p});f.animate({marginTop:0},n,function(){e.bind("click",m)})};b=function(){timer&&(k=window.setInterval(l,timer))};c=function(){timer&&window.clearInterval(k)};f.hover(c,b).mouseout();d.css("cursor","pointer").click(l).hover(c,b);e.css("cursor","pointer").click(m).hover(c,b)}})})(jQuery);